Add TL-Verilog
github-linguist/linguist pull request #5331
Opened 2021-04-19 13:36 UTC by adamint

This PR is to add TL-Verilog, an EDA language that transpiles to SystemVerilog and Verilog.

~A little about TLV~
TL-Verilog is rapidly gaining popularity for digital logic design, as an extension to Verilog (the predominant logic design language). TL-Verilog is utilized within the makerchip.com and edaplayground.com platforms and is supported by tl-x.org. GitHub integration for Makerchip is in the works.

The most popular TL-Verilog projects are:
  - https://github.com/stevehoover/warp-v
  - https://github.com/stevehoover/1st-CLaaS
These have numerous forks, stars, and external contributions.

RISC-V International lists popular RISC-V CPU core implementations, including two in TL-Verilog: https://riscv.org/exchange/cores-socs/, one from above, and one from training classes.

Hundreds (thousands?) of students have developed using TL-Verilog in online courses:
  - Linux Foundation: https://www.edx.org/course/building-a-risc-v-cpu-core
  - https://www.vlsisystemdesign.com/riscv-based-myth/,
  - https://www.udemy.com/course/vsd-pipelining-risc-v-with-transaction-level-verilog/.
and more are on the way from IEEE (https://events.vtools.ieee.org/m/248362) and Open-Source FPGA Foundation (https://osfpga.org/).

## Checklist:
- [X] **I am adding a new language.**
  - [X] The extension of the new language is used in hundreds of repositories on GitHub.com.
    - Search results for each extension:
      
      -  https://github.com/search?utf8=%E2%9C%93&type=Code&ref=searchresults&q=extension%3ATLV+KEYWORDS+NOT+nothack
  - [X] I have included a real-world usage sample for all extensions added in this PR:
    - Sample source(s):
      - [URL to each sample source, if applicable]
    - Sample license(s):
  
  - [X] I have included a syntax highlighting grammar: https://github-lightshow.herokuapp.com/?utf8=%E2%9C%93&scope=from-url&grammar_format=auto&grammar_url=https%3A%2F%2Fraw.githubusercontent.com%2Fadamint%2Ftlv-vscode%2Fmain%2Fsyntaxes%2Ftlverilog.tmLanguage&grammar_text=&code_source=from-url&code_url=https%3A%2F%2Fgithub.com%2Fstevehoover%2Fwarp-v%2Fblob%2Fmaster%2Fwarp-v_config.tlv&code=
  - [ ] I have updated the heuristics to distinguish my language from others using the same extension.

2021-04-23 08:22 UTC, lildude commented
Thanks for the PR. If we use your heuristic to filter the search results - [like this](https://github.com/search?q=extension%3Atlv+TLV_version+NOT+nothack&type=Code) - we get only 32 files on the whole of GitHub. This is a long way from our minimum requirement of 200 unique `:user/:repo` repositories so we can't accept this PR right now. Given the very low numbers it's probably best to close this PR and open a new one once usage meets our requirements.

2021-04-23 15:26 UTC, adamint commented
@lildude I'm not sure you put in the right search :smile: \TLV_version and \m4_TLV_version are both supported (and anything actually before TLV)

2021-04-26 08:40 UTC, lildude commented
🤦 I missed that the search has changed and isn't matching the `TLV_version` part of `m4_TLV_version`.  That said, adjusting the search to take this into account [`extension:tlv TLV version`](https://github.com/search?q=extension%3Atlv+TLV+version+NOT+nothack&type=Code) and pull in even more results which may not all be TL-Verilog files stills comes up considerably short:

Total files found: 457
Unique public user/repos: 81
Unique owners: 47

Even adding together the two individual specific searches doesn't meet the threshold yet:

- [`extension:tlv TLV_version`](https://github.com/search?q=extension%3Atlv+TLV_version&type=Code):

Total files found: 32
Unique public user/repos: 3
Unique owners: 3

- [`extension:tlv m4_TLV_version`](https://github.com/search?q=extension%3Atlv+m4_TLV_version&type=Code):

Total files found: 405
Unique public user/repos: 77
Unique owners: 41

2022-10-20 11:22 UTC, lildude requested changes
Looks like things are popular enough to merge this PR. Please merge in master and address the conflicts.

2022-11-14 11:49 UTC, lildude commented
> Looks like things are popular enough to merge this PR. Please merge in master and address the conflicts.

Or you can grant me write access and I'll do it.

2023-02-17 10:12 UTC, lildude commented
Please resolve the merge conflicts or grant me write access so we can merge this PR.

2023-05-30 09:35 UTC, lildude approved these changes
LGTM. Thanks.

Note: this PR will not be merged until close to when the next release is made. See [here](https://github.com/github/linguist/blob/master/docs/troubleshooting.md#my-linguist-pr-has-been-merged-but-github-doesnt-reflect-my-changes) for more details.

2023-05-30 09:42 UTC, merged