Add RBS language
github-linguist/linguist pull request #6369
Opened 2023-04-12 15:46 UTC by ybiquitous

## Description

This pull request adds the RBS language. RBS (RuBy Signature) is a language to describe the structure of Ruby programs and has been developed and maintained by the Ruby official team.

Closes #6368

## Checklist:

- [x] **I am adding a new language.**
  - [ ] The extension of the new language is used in hundreds of repositories on GitHub.com.
    - Search results for each extension:
      
      - https://github.com/search?type=code&q=path%3A**%2F%3F*.rbs
  - [x] I have included a real-world usage sample for all extensions added in this PR:
    - Sample source(s):
      - https://github.com/ruby/rbs/blob/ff85396bb230a9fce11b84ce79b4ba92900d0e6b/core/enumerator.rbs
    - Sample license(s):
      - https://github.com/ruby/rbs/blob/ff85396bb230a9fce11b84ce79b4ba92900d0e6b/COPYING
  - [x] I have included a syntax highlighting grammar: https://github.com/soutaro/vscode-rbs-syntax
      
  - [x] I have added a color
    - Hex value: `#701516`
    - Rationale: RBS is strongly integrated with Ruby and usually is used together. So, it makes sense to adopt the same color as Ruby.
  - [ ] I have updated the heuristics to distinguish my language from others using the same extension.

2023-04-14 16:56 UTC, Alhadis requested changes

2023-04-14 16:56 UTC, Alhadis commented on lib/linguist/languages.yml
> +  type: programming
This should really be categorised as data, considering [RBS syntax](https://github.com/ruby/rbs/blob/b7923d37ef8efa514aaf1624763b1408e3450bd5/docs/syntax.md#syntax) is purely descriptive in nature:

```suggestion
  type: data
```

2023-04-14 17:09 UTC, Alhadis requested changes

2023-04-14 17:09 UTC, Alhadis commented on lib/linguist/languages.yml
> +  ace_mode: text
Both [CodeMirror](https://codemirror.net/5/mode/ruby/index.html) and [ACE](https://ace.c9.io/build/kitchen-sink.html)'s Ruby modes do a decent job of highlighting RBS syntax, so they're worth reusing:

```suggestion
  ace_mode: ruby
  codemirror_mode: ruby
  codemirror_mime_type: text/x-ruby
```

2023-04-14 23:16 UTC, Alhadis approved these changes

2023-04-14 23:16 UTC, ybiquitous commented
@Alhadis Thanks for the review. I addressed all!

2023-04-14 23:23 UTC, Alhadis commented
@lildude This LGTM. 👍 Popularity requirements appear to checkout with [~10.7k search results](https://github.com/search?q=path%3A**%2F%3F*.rbs&type=code) for the `.rbs` extension (I've also encountered these files while hacking on Homebrew's source code, so I'm assuming this is a well-established and well-known file format in the Ruby community).

2023-04-14 23:39 UTC, ybiquitous commented
> I'm assuming this is a well-established and well-known file format in the Ruby community

Yes. Ruby 3.0 first released RBS as a language for static analysis (e.g. type-checking). See also the "Static Analysis" section in the [Ruby 3.0 announcement](https://www.ruby-lang.org/en/news/2020/12/25/ruby-3-0-0-released/)

Furthermore, RBS has been gradually growing with the community's support. For example, we can see many RBS files contributed by the community in the [ruby/gem_rbs_collection](https://github.com/ruby/gem_rbs_collection) repository (like DefinitelyTyped).

2023-05-08 08:57 UTC, lildude approved these changes
LGTM. Thanks.

Note: this PR will not be merged until close to when the next release is made. See [here](https://github.com/github/linguist/blob/master/docs/troubleshooting.md#my-linguist-pr-has-been-merged-but-github-doesnt-reflect-my-changes) for more details.

2023-05-13 04:23 UTC, ybiquitous commented on vendor/grammars/vscode-rbs-syntax
Hello. Thanks for the review and approval!
I noticed the grammar file had been updated since I created this PR. Here is the diff: 
https://github.com/soutaro/vscode-rbs-syntax/compare/164e36d3d39c0f187a04f7370cea7ba22453b662...master

Can I update the commit ID of `vscode-rbs-syntax`?

2023-05-13 04:25 UTC, Alhadis commented on vendor/grammars/vscode-rbs-syntax
@ybiquitous You can, but you really don't need to. Before a new release of Linguist is cut, all grammars—both old and new—are updated to their latest revisions.

2023-05-13 04:29 UTC, ybiquitous commented on vendor/grammars/vscode-rbs-syntax
@Alhadis Thanks for the quick answer! Okay, I'll leave it as-is. 👍🏼 

I'm looking forward to the next release!

2023-05-13 06:02 UTC, Alhadis commented on vendor/grammars/vscode-rbs-syntax
Our timezones are very close, so it isn't surprising that we're both on GitHub at the same time-of-day. 😁

2023-05-30 09:47 UTC, merged