feat: add support for WebAssembly Interface Type
github-linguist/linguist pull request #6376
Opened 2023-04-14 21:03 UTC by eduardomourar

## Description

Add support for WebAssembly Interface Type (WIT):
https://github.com/WebAssembly/component-model/blob/main/design/mvp/WIT.md

## Checklist:
- [x] **I am adding a new language.**
  - [x] The extension of the new language is used in hundreds of repositories on GitHub.com.
    - Search results for each extension:
      -  https://github.com/search?q=path%3A*.wit&type=code
  - [x] I have included a real-world usage sample for all extensions added in this PR:
    - Sample source(s):
      - https://github.com/WebAssembly/wasi-io/tree/e6bcf18ac5e2d2deee5016fc4b6e260fc14d4bdc/wit
    - Sample license(s): Apache 2.0
  - [x] I have included a syntax highlighting grammar: https://github.com/bytecodealliance/vscode-wit
  - [x] I have added a color
    - Hex value: `#6250e7`
    - Rationale: Based on the WebAssembly logo

2023-04-14 23:12 UTC, Alhadis requested changes
This is the first grammar I've encountered that uses `repository` fields in contexts that aren't the top-level grammar object. I see that VSCode supports this, but Atom doesn't—and by extension, that (probably) includes PrettyLights (GitHub's implementation of TextMate's highlighting system, which is closed-source).

So comments will end up looking something like this on GitHub:

<img src="https://github.com/github/linguist/assets/2346707/cef09edc-85f1-4386-abd4-b19c7125fbff" width="338" alt="Figure 1" />

This can be solved by moving every named rule to the top-level `repository` object.

2023-04-14 23:12 UTC, Alhadis commented on lib/linguist/languages.yml
> +  codemirror_mime_type: text/x-csrc
```suggestion
  codemirror_mode: webidl
  codemirror_mime_type: text/x-webidl
```

CodeMirror's [C-like mode](https://codemirror.net/5/mode/clike/) fails to highlight the following WIT fragment:

~~~
world my-world {
	import host: self.host
	import other-functionality: pkg.sibling-file
	import more-functionality: pkg.sibling-file.specific-interface
}

interface host {
	// ...
}
~~~

Its [WebIDL mode](https://codemirror.net/5/mode/webidl/index.html), OTOH, does a better—albeit still imperfect—job of highlighting WIT source. Having some highlighting is better than none at all.

2023-04-15 06:53 UTC, eduardomourar commented
The repository fields have been moved to the top-level object.

2023-04-15 08:01 UTC, Alhadis approved these changes
Alright, grammar's looking good. The syntax highlighting grammar, I mean, not that of my Dunglish:

<img src="https://github.com/github/linguist/assets/2346707/cd69c0b9-d8d6-4791-b007-09bae1274b77" width="486" alt="Figure 1" />

I noticed a few omissions in your grammar, but nothing urgent. I'll submit an issue to `vscode-wit` later with more info.

2023-04-25 15:54 UTC, Alhadis commented
/cc @lildude for license review

2023-05-30 09:45 UTC, lildude approved these changes

2023-05-30 09:47 UTC, merged