Add '.txx' extension to C++
github-linguist/linguist pull request #6380
Opened 2023-04-17 20:04 UTC by wroyca

Include support for the ".txx" file extension, which has been commonly used for C++ template implementation across various build systems. https://github.com/build2/bdep/pull/5

## Checklist:

- [x] **I am adding a new extension to a language.**
  - [x] The new extension is used in hundreds of repositories on GitHub.com
    - Search results for each extension:
      - .txx - https://github.com/search?q=path%3A*.txx&type=code
  - [x] I have included a real-world usage sample for all extensions added in this PR:
    - Sample source(s):
      - https://github.com/build2/build2/blob/a1a01cbce316c5da7aa94e6b6a71eae98bffed1c/libbuild2/target.txx#L4
      - https://github.com/Kitware/VTK/blob/6d5a55c728ee132a818da88ad48af899c9baa6ec/Common/Core/vtkSparseArray.txx#L4
      - https://github.com/hsundar/dendro/blob/f3337fc933ffaca885bf159548dfb224dbac5cbe/include/par/search.txx#L4
      - https://github.com/BelledonneCommunications/liblinphone/blob/9a4c6b714bf543a625a16c4b0b3896705b5c0f9c/libxsd/xsd/cxx/tree/serialization.txx#L4
      - https://github.com/SeanCampbell/WordAnalysis/blob/01c2edadad7644427b88ad1d0ecc7d732bb4cce9/vxl_src/core/vil1/vil1_rgba.txx#L4
      - https://github.com/IMFTool/IMFTool/blob/71a0e5f15dfe8e9fe3237040e5ab4528ee56f2d2/src/synthesis/xsd/cxx/tree/types.txx#L4
      - https://github.com/nessus42/astronomical-medicine/blob/ef51b2ebca94fe840da5d1e91b80c46e4ce9b21a/itkFITSWCSTransform.txx#L4
      - https://github.com/malaterre/GDCM/blob/82cff8ea33ca9eb25f4a777fd92b08785b5d6d06/Source/DataStructureAndEncodingDefinition/gdcmDataSet.txx#L4
      - ...
    - Sample license(s):
  - [ ] I have included a change to the heuristics to distinguish my language from others using the same extension.

- [ ] **I am adding a new language.**
  - [ ] The extension of the new language is used in hundreds of repositories on GitHub.com.
    - Search results for each extension:
      
      -  https://github.com/search?utf8=%E2%9C%93&type=Code&ref=searchresults&q=extension%3AFOOBAR+KEYWORDS+NOT+nothack
  - [ ] I have included a real-world usage sample for all extensions added in this PR:
    - Sample source(s):
      - [URL to each sample source, if applicable]
    - Sample license(s):
  - [ ] I have included a syntax highlighting grammar: [URL to grammar repo]
      
  - [ ] I have added a color
    - Hex value: `#RRGGBB`
    - Rationale: 
  - [ ] I have updated the heuristics to distinguish my language from others using the same extension.

- [ ] **I am fixing a misclassified language**
  - [ ] I have included a new sample for the misclassified language:
    - Sample source(s):
      - [URL to each sample source, if applicable]
    - Sample license(s):
  - [ ] I have included a change to the heuristics to distinguish my language from others using the same extension.

- [ ] **I am changing the source of a syntax highlighting grammar**
  - Old: [URL to grammar repo]
  - New: [URL to grammar repo]

- [ ] **I am updating a grammar submodule**
  

- [ ] **I am adding new or changing current functionality**
  
  - [ ] I have added or updated the tests for the new or changed functionality.

- [ ] **I am changing the color associated with a language**
  
  - [ ] I have obtained agreement from the wider language community on this color change.
    - [URL to public discussion]
    - [Optional: URL to official branding guidelines for the language]

2023-04-18 07:36 UTC, lildude requested changes
Please add one to three of the most representative samples you have referenced to the C++ samples directory… we need the actual files to train the classifier, not just the links 😉

2023-04-18 11:38 UTC, wroyca commented
> Please add one to three of the most representative samples you have referenced to the C++ samples directory… we need the actual files to train the classifier, not just the links wink

Oops, done. Thank! :rocket:

2023-04-18 13:01 UTC, lildude approved these changes
LGTM. Thanks.

Note: this PR will not be merged until close to when the next release is made. See [here](https://github.com/github/linguist/blob/master/docs/troubleshooting.md#my-linguist-pr-has-been-merged-but-github-doesnt-reflect-my-changes) for more details.

2023-05-30 09:45 UTC, lildude approved these changes

2023-05-30 09:47 UTC, merged