Mark files under `htmlcov/` as generated
github-linguist/linguist pull request #6491
Opened 2023-07-26 12:42 UTC by spenserblack

## Description
This marks files generated by [coverage.py](https://github.com/nedbat/coveragepy), specifically the `coverage html` command, as generated. There are currently [quite a lot](https://github.com/search?q=path%3A%2F%28%5E%7C%5C%2F%29htmlcov%5C%2F%2F&type=code) of these files that are returned by GitHub's search, and it seems like the large majority come from this tool ([more specific search results](https://github.com/search?q=path%3A%2F%28%5E%7C%5C%2F%29htmlcov%5C%2F.%2B_py%5C.html%24%2F&type=code)).

## Checklist:

- [x] **I am adding new or changing current functionality**
  - [ ] I have added or updated the tests for the new or changed functionality.

2023-07-26 13:23 UTC, spenserblack commented
I appear to be making some sort of mistake.
Tests fail, but running this locally seems to work fine (got the expected `appears to be generated source code` output for `htmlcov/index.html`).

2023-07-26 14:00 UTC, spenserblack commented
Oh, of course. It helps to actually *read* the failure message. Moved the check up the chain of `||`s so that it's checked before any HTML, JS, or CSS is read.

Anyway, opening it back up for review. I'm anticipating that maybe some method renaming and/or combining with other methods may be requested :slightly_smiling_face:

2023-08-19 14:48 UTC, Alhadis requested changes
Minor nitpick concerning naming; ~~don't forget to move the method definition to its alphabetically-appropriate location in `generated.rb`~~ Scratch that, the file's not ordered anyway. 😅

2023-08-19 17:50 UTC, spenserblack commented on lib/linguist/generated.rb
> +      coveragepy_htmlcov_file? ||
Good point, thanks!

2023-08-19 20:59 UTC, Alhadis approved these changes

2023-09-07 10:48 UTC, merged