Update color for Sway
github-linguist/linguist pull request #6498
Opened 2023-08-02 21:35 UTC by sdankel

Changing the color for the Sway language to Fuel Labs' green.

## Checklist:
- [ ] **I am adding a new extension to a language.**
  - [ ] The new extension is used in hundreds of repositories on GitHub.com
    - Search results for each extension:
      
      - https://github.com/search?type=code&q=NOT+is%3Afork+path%3A*.FOOBAR+KEYWORDS
  - [ ] I have included a real-world usage sample for all extensions added in this PR:
    - Sample source(s):
      - [URL to each sample source, if applicable]
    - Sample license(s):
  - [ ] I have included a change to the heuristics to distinguish my language from others using the same extension.

- [ ] **I am adding a new language.**
  - [ ] The extension of the new language is used in hundreds of repositories on GitHub.com.
    - Search results for each extension:
      
      -  https://github.com/search?type=code&q=NOT+is%3Afork+path%3A*.FOOBAR+KEYWORDS
  - [ ] I have included a real-world usage sample for all extensions added in this PR:
    - Sample source(s):
      - [URL to each sample source, if applicable]
    - Sample license(s):
  - [ ] I have included a syntax highlighting grammar: [URL to grammar repo]
      
  - [ ] I have added a color
    - Hex value: `#RRGGBB`
    - Rationale: 
  - [ ] I have updated the heuristics to distinguish my language from others using the same extension.

- [ ] **I am fixing a misclassified language**
  - [ ] I have included a new sample for the misclassified language:
    - Sample source(s):
      - [URL to each sample source, if applicable]
    - Sample license(s):
  - [ ] I have included a change to the heuristics to distinguish my language from others using the same extension.

- [ ] **I am changing the source of a syntax highlighting grammar**
  - Old: [URL to grammar repo]
  - New: [URL to grammar repo]

- [ ] **I am updating a grammar submodule**
  

- [ ] **I am adding new or changing current functionality**
  
  - [ ] I have added or updated the tests for the new or changed functionality.

- [x] **I am changing the color associated with a language**
  
  - [x] I have obtained agreement from the wider language community on this color change.
    - [URL to public discussion]
    - [Optional: URL to official branding guidelines for the language]

2023-10-31 08:05 UTC, lildude requested changes
>  I have obtained agreement from the wider language community on this color change.
[URL to public discussion]
[Optional: URL to official branding guidelines for the language]

No you haven't 😉

You can't blindly change the language without filling this in. This is strictly enforced as people are sensitive about these things.

See https://github.com/github-linguist/linguist/blob/master/CONTRIBUTING.md#changing-the-color-associated-with-a-language for more details

2023-10-31 18:52 UTC, sdankel commented on lib/linguist/languages.yml
> +  color: "#08f48c"
```suggestion
  color: "#00F58C"
```

2023-10-31 19:02 UTC, sdankel commented
Putting this back in draft as the design team discusses internally. They'll post on this PR when a decision is reached.

2023-10-31 20:25 UTC, lildude commented
> Public discussion on this PR

Please don’t. The discussion needs to take place publicly in your community forums and referenced in this PR. Not here.

2023-11-22 22:20 UTC, sdankel commented
@lildude I updated the link to our community forum with discussion and a poll. Let me know if this works.

2023-11-24 09:08 UTC, lildude approved these changes
LGTM. Thanks.

Note: this PR will not be merged until close to when the next release is made. See [here](https://github.com/github/linguist/blob/master/docs/troubleshooting.md#my-linguist-pr-has-been-merged-but-github-doesnt-reflect-my-changes) for more details.

2023-12-05 08:08 UTC, merged