Add missing GLSL vertex shader extension
github-linguist/linguist pull request #6536
Opened 2023-09-06 01:33 UTC by FrostKiwi

Added missing `.vs` extension to recognize `.vs` files as `GLSL`.
For GLSL fragment shaders it is common to have either `.fs` or `.frag` as your file extension. Both are present in [this line of `languages.yml`](https://github.com/github-linguist/linguist/blob/916bd8f3df802fa98b0ea85539e67bd0b88ef158/lib/linguist/languages.yml#L2166). For the vertex shader however, only `.vert` is present and the counterpart to `.fs`, `.vs` has been forgotten. This has been fixed with this PR
## Description
This solves GitHub support ticket #2320418, which had the following issue:
<details><summary>Issue caused by .vs not being in linguist</summary>

The main GitHub website does Syntax Highlighting based on the language it detects. It also shows a repo's language breakdown:
![image](https://github.com/github-linguist/linguist/assets/60887273/48983e57-d96b-499c-a69a-727c983ee7c0)

This feature has a bug when detecting GLSL Shaders. You can observe this bug in my repo: https://github.com/FrostKiwi/Mirrorball
Take a look at the detected GLSL shaders: https://github.com/search?q=repo%3AFrostKiwi%2FMirrorball++language%3AGLSL&type=code and what is actually in that directory: https://github.com/FrostKiwi/Mirrorball/tree/main/src/shd

You see two file types.
 * The GLSL Fragment Shaders with a .fs file extension.
   * File type properly detected as GLSL and syntax highlighting present: 
![image](https://github.com/github-linguist/linguist/assets/60887273/eacd46a7-c8bd-4462-8175-168cd8027505)

 * The GLSL Vertex Shaders with a .vs file extension
   * File type not properly detected as GLSL and no syntax highlighting present: 
![image](https://github.com/github-linguist/linguist/assets/60887273/86c95618-6929-4ac2-8b38-4a4222a19e88)
   * Furthermore, these files are not listed in the Language breakdown: https://github.com/search?q=repo%3AFrostKiwi%2FMirrorball++language%3AGLSL&type=code

.fs for fragment shaders and .vs for vertex shaders are a common choise along side .frag and .vert. So this is not a repo-specific naming, but a common one.
</details>

## Checklist:

- [x] **I am adding a new extension to a language.**
  - [x] The new extension is used in hundreds of repositories on GitHub.com
    - Search results for each extension:
      
      - https://github.com/search?type=code&q=NOT+is%3Afork+path%3A*.FOOBAR+KEYWORDS
  - [X] I have included a real-world usage sample for all extensions added in this PR:
    - Sample source(s) (Note the missing syntax highlighting of `.vs` files, but all `.fs` in those same repos have it):
      - https://github.com/google/filament/blob/d11a782c3e73ce705395682ad7503ddd9f5d9f74/shaders/src/main.vs#L4 
      - https://github.com/FrostKiwi/Mirrorball/blob/main/src/shd/crop.vs 
      - https://github.com/RandyGaul/cute_headers/blob/265f675325629f3bae5710c6f1362bba9f619357/examples_cute_gl_and_c2/simple.vs#L4
    - Sample license(s):
  - [ ] I have included a change to the heuristics to distinguish my language from others using the same extension.
    - Not necessary, already present for `GLSL` and `.vs` is unique to `GLSL`, at least in linguist.
- Does not apply:
  - [ ] **I am adding a new language.**
  - [ ] **I am fixing a misclassified language**
  - [ ] **I am changing the source of a syntax highlighting grammar**
  - [ ] **I am updating a grammar submodule**
  - [ ] **I am adding new or changing current functionality**
  - [ ] I have added or updated the tests for the new or changed functionality.
  - [ ] **I am changing the color associated with a language**
  
  - [ ] I have obtained agreement from the wider language community on this color change.
    - Not sure this is needed in this case, seeing as `.fs` has been accepted, but `.vs` has been forgotten, the

2023-09-06 02:42 UTC, lildude requested changes
Please add the samples you've referenced in the template to the PR in the GLSL samples directory and update the template to state the licence of each file. ProTip: if the file is not shown fully in the diff, it's too big so should be replaced with a smaller file. Two samples should be plenty so pick two that differ the most (these are used to train the classifier).

Please also update the search query in the template.

2023-09-06 03:55 UTC, FrostKiwi commented
> Please add the samples you've referenced in the template to the PR in the GLSL samples directory and update the template to state the licence of each file. ProTip: if the file is not shown fully in the diff, it's too big so should be replaced with a smaller file. Two samples should be plenty so pick two that differ the most (these are used to train the classifier).
> 
> Please also update the search query in the template.

Updated to reflected the requested changes.

2023-09-07 08:54 UTC, lildude commented on lib/linguist/languages.yml
> +  - ".vs"
```suggestion
  - ".vs"
  - ".vsh"
  - ".vshader"
```

2023-09-07 10:45 UTC, lildude approved these changes

2023-09-07 10:49 UTC, merged