Replace Open Policy Agent grammar
github-linguist/linguist pull request #6575
Opened 2023-10-11 20:59 UTC by ashutosh-narkar

## Description

This PR updates the source of the Open Policy Agent grammar.

## Checklist:

- [x] **I am changing the source of a syntax highlighting grammar**
  - Old: https://github.com/tsandall/vscode-opa
  - New: https://github.com/open-policy-agent/vscode-opa

2023-10-12 07:38 UTC, lildude commented
Why the change? The original appears to be a fork of the new with added functionality. We don't want to lose functionality when changing. /cc @tsandall as the owner of the fork and current grammar.

2023-10-12 21:27 UTC, ashutosh-narkar commented
> Why the change? The original appears to be a fork of the new with added functionality. We don't want to lose functionality when changing. /cc @tsandall as the owner of the fork and current grammar.

We should not lose functionality if we switch. The new repo is actively maintained and the latest grammar updates will be pushed to it. cc @tsandall

2023-10-12 21:30 UTC, tsandall commented
👋 yep, this should point at github.com/open-policy-agent/vscode-opa rather than my fork.

2023-10-18 16:25 UTC, lildude requested changes
An updated copy of the license file should have been downloaded when you ran `script/add-grammar --replace` as detailed in the docs. Please add this updated cached license file to this PR.

If you can't find it, you can run: `bundle exec licensed cache -c vendor/licenses/config.yml`

2023-10-18 22:26 UTC, ashutosh-narkar commented
> An updated copy of the license file should have been downloaded when you ran `script/add-grammar --replace` as detailed in the docs. Please add this updated cached license file to this PR.
> 
> If you can't find it, you can run: `bundle exec licensed cache -c vendor/licenses/config.yml`

I ran `bundle exec licensed cache -c vendor/licenses/config.yml` and get the below ouput. I don't see any new files in my working tree. Also the contents of `vendor/licenses/git_submodule/vscode-opa.dep.yml` seem to be same as the current version. I'm probably missing something so would appreciate your help here.

```
$ bundle exec licensed cache -c vendor/licenses/config.yml
Caching dependency records for linguist
  git_submodule
    Using AL (b7ee43a4f93e35e56c7a12316aed548c470a8406)
    Using Alloy.tmbundle (0a80fc74e921325da23264889771a88a02877414)
    Using Assembly-Syntax-Definition (519b7b3c5f8428832dde72a90041d0707f831e5c)
    Using Atom-PostScript (3a3d50683c198a7af5543be1d47ba33d21bb373f)
    Using AtomLanguageVelocity (6eb92de5a24991192192d768241be12337015884)
    Using AutoHotkey (279f16cef09be8d47dc33dc763f4a58079b4a81d)
    Using CUE-Sheet_sublime (7f099baf680744f62336edc8d7c3009187f5e572)
    Using CoDT7-Sublime (c078fc6e5ff116e3170de896521824fd096853e1)
    Using CodeMirror (53faa33ac69598b7495e160824b58ebb8d70fe97)
    Using ColdFusion (dbe2f76038fe77fe90b4cc4a0651aa817f14f1a3)
    Using Dafny-VSCode (55044e501fe916d87fa6504c2dec6ac6012aaddf)
    Using Docker.tmbundle (0f6b7bc87acf684f7b0790fd480731ffb4615b87)
    Using Elm (80809a07ecfd7682f96e0ea775fdf30bce68e6fb)
    Using FreeMarker.tmbundle (7259485a01310af4bf63ba4ff37cbba3724ae77f)
    Using Handlebars (c2c09947b6b83d740e9ee94a6e3a0199476f2e15)
    Using IDL-Syntax (0fc6b8f6f6696f612e70b56ff086b3eec4d39b7d)
    Using Isabelle.tmbundle (745c337a0432270474f50d12fad7ea4aa9e0b169)
    Using JSyntax (b20c93c2e8a8704934d991120e75a32cb53e9cb4)
    Using LOLCODE-grammar-vscode (2091c60ebe0b20e169853e5a0385b4bfb54c86f0)
    Using Ligo-grammar (73ffbf6f2b63b861d9f5165c5a64e8d4eee06ea1)
    Using LiveScript.tmbundle (d82aeb737d4883d1a74aba7a07053f90211d427b)
    Using MATLAB-Language-grammar (c2c0e4ec8a401b2c6f76e6069aa0b19da3d0b3bd)
    Using MQL5-sublime (a41ed3b5e5af354d9faf262794549ea44bbe5912)
    Using MagicPython (7d0f2b22a5ad8fccbd7341bc7b7a715169283044)
    Using Modelica (c64d74b0096e7ebf5fbf1bb6812203b9b1292d6a)
    Using NSIS (696d06cb2bd0dfc619c989c746e4b43eea689161)
    Using Nasal.tmbundle (856bd56438b2ca2a82676b461dcebbe74e75600c)
    Using NimLime (6297c32c11fd92eb9bc3c5cd09a9ff79b7f3d4f9)
    Using NovaGrammars (c6e3be72f19b428141bb31b55f15b9815b3ee329)
    Using ObjectScript.tmBundle (0b7465b7f93f65c6d649358b43272b2888c71f7a)
    Using PHP-Twig.tmbundle (aedf955eba9753554815b2cbef5e072415e42068)
    Using PogoScript.tmbundle (2255586f9ec69bab052b2250615db9b824774178)
    Using RDoc.tmbundle (6a403e7e2fc8800133075e27fa55f30a7885c41a)
    Using Racket (02739c25aefb484a031e58ff7a628adf4c97225f)
    Using SMT.tmbundle (426d5f7e0a5303fedfff2465d30165dcb4fae675)
    Using Scalate.tmbundle (0307535add076965c8cd438d0f4109bec7d68d2d)
    Using Scenic-tmLanguage (67ef2ebfc97fb159c063a1d8276322357c11825b)
    Using Slash.tmbundle (48e678eb2797295190f0dfa324167d0006bcc4e3)
    Using Stata.tmbundle (50685c273588cf6bd4828cb30432c7152df91c4e)
    Using Stylus (30908e3b5757d6cab4bf2ce660ef89b0c614cf62)
    Using Sublime-Coq (0d1f70727b19007e55780bcd7b74f70c399eba3b)
    Using Sublime-HTTP (9938a52ba113bb1e58eee8fc91878827c2967f59)
    Using Sublime-Lasso (c755cf53bed8f81dcfbe937f9feaa9e564f1c2a9)
    Using Sublime-Loom (725228409c4cfcbf00216d677b85466b2303ef0b)
    Using Sublime-Modula-2 (9bd5077f925ac7a3edc87d45d1f872593ff7377e)
    Using Sublime-Nit (12c1d654166cab044fbab2d1d7f481930ad7777c)
    Using Sublime-Pep8 (be653c638b2b042c90384f5d3f335d93172bcd85)
    Using Sublime-QML (e3e058a21f3c44d64ef5eda93925ee84169b62ec)
    Using Sublime-REBOL (da2b4ec0c84d6e593698118061efb4bd64eff853)
    Using Sublime-Red (fb0c69926e2f966dab413f1c34a05f376317a319)
    Using Sublime-SQF-Language (839dd534d110face46f09bfcd120cc8d8041b2d1)
    Using SublimeBrainfuck (4fda534b0edfba46f1e0d920aad5f519746f2ab2)
    Using SublimeClarion (b3597c7c993c60b2813ace6129165e6c5e9390fc)
    Using SublimeEthereum (98e4c26e6e7236eca752c2f3d0c70f076c0598df)
    Using SublimeGDB (fcd83adef823885874a84bab184e086c94f689cc)
    Using SublimePapyrus (6dc86d921a20573fb1be6f076a0022d4d28629e4)
    Using SublimePuppet (2a224343d2151b2896b6d9c48343919c06d1e695)
    Using SublimeXtend (61c06e16645078c3238a23548911c8cd147e4b69)
    Using Syntax-highlighting-for-PostCSS (575b918985ce82545a12615a244243e41a91cd52)
    Using SystemVerilog (7eca705e87f87b94478fe222fc91d54d488cc8e3)
    Using TLA (a67cbd03099df412db00cae78d23c836b79ebc2b)
    Using TXL (614cf836497338efb87909ce54700b2e18c9fa04)
    Using Terraform.tmLanguage (7faec10b4057b95bff82fb585730e560871d26c4)
    Using Textmate-Gosu-Bundle (c0e36a01ba2c82d87fd6623481fbb57a5055b376)
    Using TypeScript-TmLanguage (82dcf60b94c305088165eff5c7e14b07f6048b22)
    Using UrWeb-Language-Definition (cd47cc78918244b9cc36f57f5397a97a5affce4e)
    Using VBDotNetSyntax (efaa4187fe75634c0f01c294c0d9624d141cd649)
    Using Vala-TMBundle (935bd21c13068158435f64b3dbd8423c8d812c92)
    Using VscodeAdblockSyntax (bbd868b4288bf03cb3a2551b5ef35b2103e5a70f)
    Using WhileySyntaxBundle (2dd042aa33069784e741bba943e8697ea358d449)
    Using X10 (2bae6e77fabcdceff753823477390c37305ca76c)
    Using XojoSyntaxTM (3497e2443b5763353e63a32deed727f6d710f073)
    Using ZenScript-tmLanguage (5a7bcb775a6fb37470e56f904e70d8b8b9e6b047)
    Using abap-cds-grammar (14d892fb0eb8bd98b0340a2b6d265cbeeb938884)
    Using abap.tmbundle (a9b2efff4f4afa469d984353384f09e4ebd24055)
    Using abl-tmlanguage (e928116b4138bcf191b6f64be5bf92ef9c345d75)
    Using actionscript3-tmbundle (bb76f18706fdba78ffce2dd7d32ed3d2c061ba1a)
    Using ada.tmbundle (59bfc50221b2dcdbdb8a98117f44e66e1c35ffcf)
    Using agda-github-syntax-highlighting (ba7aef428c0b900675696de17e1ee6bc9d7e684e)
    Using aidl-language (ce07cdf6b9b9dbc4857c4b2fc59a55ac0e17ecd4)
    Using ampl (2e399ebf4aec6b5b81f01d4cbee965f77852ce86)
    Using android-system-tools (307f6c9c0b0b305d6cf72480a37a72d0f86077f1)
    Using ant.tmbundle (156b6945262da1c53c1d83a411dbac126f06195d)
    Using antlr.tmbundle (7f07385abbdbd716ebb5b15ad8190347554192cf)
    Using apache.tmbundle (a12e895533700b0200cca20f169be63727efff8c)
    Using apex-tmLanguage (88b3b7175cc0be3edf7e22cf8eecc32911740b05)
    Using api-blueprint-sublime-plugin (0a90eff10e71a8f18974410307b3b86c71afb3ed)
    Using applescript.tmbundle (4947cad7494eba084c21cfe04689b4efce96700f)
    Using asciidoc.tmbundle (0c93369ddd920629bc97bf10e7270d8ec0d0463b)
    Using asp.tmbundle (144b21081aa53b8856f839aea68a724312f6001d)
    Using assembly (0ef23e8619103e87a0a90df1b96c2567fbedf7f5)
    Using astro (1e84fac22fb3ed6686ec4d5f963a0420ba2d7d82)
    Using atom-editorconfig (b5951387ac5e8fad7de6eec683436af1080badfa)
    Using atom-firestore-grammar (750ec2abef42f7061c6bcc29ed5db3b0a1f3f773)
    Using atom-fstar (05592abc84201bf1c59fc7fa000c49c781980170)
    Using atom-language-1c-bsl (289454b53797ddc6fe193486c5a08310c214da7e)
    Using atom-language-cairo (4cfbe081194875d805cdf6aa89a7024e722b20c8)
    Using atom-language-clean (82829c50aafb2d57423e3ec66c405e3eb9e97a02)
    Using atom-language-haproxy (c7313aca269b63b3879502b3939a1c09c6182860)
    Using atom-language-innosetup (9997c32bb49054eb0eb2bf429249590b8990f7cd)
    Using atom-language-julia (134a10664d7b9010af432f4042637c16fd61fe2b)
    Using atom-language-nextflow (40387695d768dc7c9ab7b8594cd2c925fd254e47)
    Using atom-language-p4 (a349af898dbe060fd548040fa352233d865aef8e)
    Using atom-language-perl6 (8c196e381edb0e5575db611bad4ca7de8b437d66)
    Using atom-language-purescript (b5c439559b21af03578d923ed8811cb0609d2210)
    Using atom-language-stan (faca857fe70a801ec941b30e6b387268 [...]

2023-10-25 09:37 UTC, lildude commented
Fixed it. Seems when the grammar was replaced it didn't pull the latest version. I updated the grammar with `git submodule update --remote -- vendor/grammars/vscode-opa`, committed the update and was then able to update the cached version.

2023-10-25 09:38 UTC, lildude approved these changes
LGTM. Thanks.

Note: this PR will not be merged until close to when the next release is made. See [here](https://github.com/github/linguist/blob/master/docs/troubleshooting.md#my-linguist-pr-has-been-merged-but-github-doesnt-reflect-my-changes) for more details.

2023-10-25 20:57 UTC, ashutosh-narkar commented
> LGTM. Thanks.
> 
> Note: this PR will not be merged until close to when the next release is made. See [here](https://github.com/github/linguist/blob/master/docs/troubleshooting.md#my-linguist-pr-has-been-merged-but-github-doesnt-reflect-my-changes) for more details.

Sounds good. Thanks for the help @lildude! I appreciate it.

2023-12-05 08:09 UTC, merged