Change DM grammar to SpaceManiac/vscode-dm-langclient
github-linguist/linguist pull request #6605
Opened 2023-11-08 10:08 UTC by vvvv-vvvv

## Description

Changed the DM grammar to a better maintained source that has new keywords

## Checklist:

- [x] **I am changing the source of a syntax highlighting grammar**
  - Old: https://github.com/PJB3005/atomic-dreams
  - New: https://github.com/SpaceManiac/vscode-dm-langclient

2023-11-08 10:37 UTC, lildude requested changes
We can't accept this change. 

Whilst the grammar files are licensed under MIT, the over-all repo is licensed by GPL-3 which means we'll be shipping code that is covered by this license which we can't do.

I'm also not sure GPL3 allows sub-licensing, but that's not relevant as we don't include just the grammar files.

2023-11-09 01:44 UTC, vvvv-vvvv commented
Is this fine? The samples for the new extensions are about as complicated as they can get, so they aren't from a real-world project

2023-11-09 08:01 UTC, lildude commented
No. We want real world examples as documented. This is used to train the classifier. The `.dme` extension is also not popular enough for addition right now so will only hold back this PR.

2023-11-09 16:39 UTC, lildude approved these changes
LGTM. Thanks.

Note: this PR will not be merged until close to when the next release is made. See [here](https://github.com/github/linguist/blob/master/docs/troubleshooting.md#my-linguist-pr-has-been-merged-but-github-doesnt-reflect-my-changes) for more details.

2023-11-29 08:44 UTC, vvvv-vvvv commented
Moved the repo elsewhere

2023-11-29 09:24 UTC, vvvv-vvvv commented on vendor/licenses/git_submodule/dm-syntax.dep.yml
> +homepage: https://github.com/vvvv-vvvv/dm-syntax.git
I did, and it didn't replace this

2023-12-05 08:10 UTC, merged

2023-12-05 19:07 UTC, optimumtact commented
thanks lildude