Update languages.yml to recognize expect as a form of Tcl
github-linguist/linguist pull request #6614
Opened 2023-11-12 22:10 UTC by cooljeanius

Closes #6613

## Description
Expect is an extension to the Tcl scripting language, so it can be categorized as Tcl. See #6613

## Checklist:
- [x] **I am adding a new extension to a language.**
  - [x] The new extension is used in hundreds of repositories on GitHub.com
    - Search results for each extension:
      - https://github.com/search?type=code&q=NOT+is%3Afork+path%3A*.exp+proc
  - [ ] I have included a real-world usage sample for all extensions added in this PR:
    - Sample source(s):
      - https://github.com/gcc-mirror/gcc/blob/master/gcc/testsuite/lib/compat.exp
    - Sample license(s):
      - GPLv3+ 
  - [ ] I have included a change to the heuristics to distinguish my language from others using the same extension.

2023-11-12 23:51 UTC, cooljeanius commented
OK I think this is ready for review now; I don't think a new heuristic is necessary, since I don't see anything else using the `.exp` extension that would need to be distinguished from.

2023-11-13 10:12 UTC, Alhadis requested changes
> I don't think a new heuristic is necessary, since I don't see anything else using the `.exp` extension that would need to be distinguished from.

I just remembered that `.exp` is sometimes used in test-suites to contain the <samp><ins>exp</ins></samp>ected output of a test run. It's usually paired with a file ending in `.act` (to denote the <samp><ins>act</ins></samp>ual output from a test), which is compared with the `.exp` file using the <samp>diff(1)</samp> utility.

There also appear to be [roughly ~203k search results](https://github.com/search?q=path%3A**%2F%3F*.exp+NOT+%2F%5E%5Cs*%28%3F%3Aset%7Cexpect%29%5Cs%2F&type=code) for the `.exp` extension that doesn't include lines beginning with `set` or `expect`. They don't appear to be fixtures for a test-suite either, so this might warrant a more in-depth investation.

2023-11-15 03:25 UTC, cooljeanius commented
> > I don't think a new heuristic is necessary, since I don't see anything else using the `.exp` extension that would need to be distinguished from.
> 
> I just remembered that `.exp` is sometimes used in test-suites to contain the expected output of a test run. It's usually paired with a file ending in `.act` (to denote the actual output from a test), which is compared with the `.exp` file using the diff(1) utility.
> 
> There also appear to be [roughly ~203k search results](https://github.com/search?q=path%3A**%2F%3F*.exp+NOT+%2F%5E%5Cs*%28%3F%3Aset%7Cexpect%29%5Cs%2F&type=code) for the `.exp` extension that doesn't include lines beginning with `set` or `expect`. They don't appear to be fixtures for a test-suite either, so this might warrant a more in-depth investation.

Hm, so maybe just a really simple heuristic then? e.g. `'^\s*(?:set|expect|proc)\s'` or something... (I'm not very good at regexes, so please correct me if I got it wrong)

2023-11-30 04:52 UTC, Alhadis commented
> Hm, so maybe just a really simple heuristic then?

Actually, I was thinking `.exp` might need to be registered as a [generic extension](https://github.com/github-linguist/linguist/blob/9358f090deb76511b613ab024b704c1c0f13a4c2/lib/linguist/generic.yml). This is a more esoteric feature of Linguist that's called upon when an extension has widespread usage in unrelated contexts, but none of them have enough adoption individually to merit their own entries in `languages.yml`. The original use-case was to support Solidity's `.sol` extension without misclassifying the numerous repositories that used `.sol` as an abbreviated suffix for _"solution"_.

However, generic extensions have the caveat that an accurate, airtight heuristic is needed, preferably one that matches a pattern or string that's all but guaranteed to appear in the files that we're interested in supporting. The regex <code>^\s*(?:set|expect|proc)\s</code> will match any line that happens to begin with the word "set", "expect" or "proc", followed by a whitespace character (including a newline). Needless to say, that's very, *very* error-prone; even if we weren't looking to add a generic extension, I still wouldn't recommend such an open-ended heuristic.

I'm happy to help you with penning the regex, but that assumes there even _is_ a predictable and guaranteed pattern unique to Expect scripts.

2025-03-12 07:57 UTC, closed without merging