Add Slint
github-linguist/linguist pull request #6750
Opened 2024-03-12 15:27 UTC by ogoffart

## Description

Add the [Slint](https://slint.dev) language

## Checklist:

- [X] **I am adding a new language.**
  - [X] The extension of the new language is used in hundreds of repositories on GitHub.com.
    - Search results for each extension:
      -  https://github.com/search?q=path%3A*.slint+-is%3Afork+-repo%3Aslint-ui%2Fslint&type=code
  - [X] I have included a real-world usage sample for all extensions added in this PR:
    - Sample source(s):
      - Coming from the examples in https://github.com/slint-ui/slint
    - Sample license(s): MIT
  - [X] I have included a syntax highlighting grammar: https://github.com/slint-ui/slint-tmLanguage
      
  - [X] I have added a color
    - Hex value: `#2379F4`
    - Rationale: Color mentioned there: https://github.com/slint-ui/slint/tree/master/logo#color
  - [ ] I have updated the heuristics to distinguish my language from others using the same extension.
    - I don't think there are other languages with the same extension

2024-03-12 15:50 UTC, lildude requested changes
Two of your samples are too big as they're being suppressed by the diff by default. Please replace these with smaller samples.

You need to also add the cached license `.yml` file that would have been created when you ran `script/add-grammar` to add the grammar.

2024-03-12 16:09 UTC, ogoffart commented
> Two of your samples are too big as they're being suppressed by the diff by default. Please replace these with smaller samples.

I edited them to removed big parts so they are small enough.

> You need to also add the cached license .yml file that would have been created when you ran script/add-grammar to add the grammar.

Added.

2024-03-12 16:18 UTC, lildude commented on vendor/licenses/git_submodule/slint-tmLanguage.dep.yml
> +notices: []
This should be populated with the deets of the license from this repo.

Try manually running this command https://github.com/github-linguist/linguist/blob/ca188d5b069684d5160170e2ab86fa995ca7fe0f/script/add-grammar#L134

2024-03-12 17:11 UTC, ogoffart commented
I had forgotten to `git add` this file. I tried to clean everything and re-create it and that didn't work at first. Now this should be the correct one.

2024-03-12 19:53 UTC, lildude commented
> I had forgotten to `git add` this file. I tried to clean everything and re-create it and that didn't work at first. Now this should be the correct one.

Whoops! There's only one file change now.

2024-03-12 23:21 UTC, ogoffart commented
> Whoops! There's only one file change now.

Sorry about that. 
I'm doing this in codespaces which I'm not familiar with. Should be alright now.

2024-03-13 10:34 UTC, lildude approved these changes
All looks good now.

2024-03-13 10:40 UTC, merged