Add Cron table language
github-linguist/linguist pull request #6759
Opened 2024-03-17 10:21 UTC by Nixinova

- Resolves #6547

## Description

Adds highlighting for Cron files of file name `crontab`.

## Checklist:

- [x] **I am adding a new language.**
  - [x] The extension of the new language is used in hundreds of repositories on GitHub.com.
    - Search results for each extension:
      - [filename 'crontab'](https://github.com/search?q=path%3A**%2Fcrontab&type=code&p=1): 6.1K+ results
  - [x] I have included a real-world usage sample for all extensions added in this PR:
    - Sample source(s):
      - [okfn-brasil/serenata-de-amor](https://github.com/okfn-brasil/serenata-de-amor/blob/e7aeba78100b1ec96c2a79a85d6f5dfd1a8adaf7/contrib/crontab/crontab#L4)
    - Sample license(s):
      - [MIT](https://github.com/okfn-brasil/serenata-de-amor?tab=MIT-1-ov-file#readme)
  - [x] I have included a syntax highlighting grammar:
    - https://github.com/textmate/cron.tmbundle 
      - (License is custom/nonstandard, but is clearly an exceptionless free license)
    
  - [❌] I have added a color
    - Don't know what to put, there's no logo or company involved.
  - [❌] I have updated the heuristics to distinguish my language from others using the same extension.

2024-03-17 12:34 UTC, Alhadis commented
> Don't know what to put, there's no logo or company involved.

Then fallback on some artistic license. 😉 I'd use the colour of a manilla folder. **Rationale:* Tables and scheduled tasks evoke images of dusty old offices with stuff that needs to be done. Hell, [this](https://paintman.co.uk/shop/manilla-bs367-standard-colour/) works: `#ead7ac`.

Otherwise, looks good. TextMate's crontab grammar is pretty solid. I've been using it in Atom without a hitch:

<img width="699" alt="Screen Shot 2024-03-17 at 11 34 15 pm" src="https://github.com/github-linguist/linguist/assets/2346707/fcddfd5a-629d-4874-a481-fa2f60430fa2">

2024-03-17 13:10 UTC, Alhadis requested changes

2024-03-17 13:10 UTC, Alhadis commented on lib/linguist/languages.yml
> +  ace_mode: text
ACE's Tcl mode does a good job of [highlighting](https://ace.c9.io/build/kitchen-sink.html) <samp>cron(8)</samp> tables:
<img src="https://github.com/github-linguist/linguist/assets/2346707/0ec97725-bbb9-422f-9cc5-ab43742d96c7" width="853" alt="ACE's Tcl mode highlighting PR's crontab sample"/>
```suggestion
  ace_mode: tcl
```

2024-03-17 13:10 UTC, Alhadis commented on lib/linguist/languages.yml
> +  type: data
The colour I [suggested](https://github.com/github-linguist/linguist/pull/6759#issuecomment-2002443424) earlier:
```suggestion
crontab:
  type: data
  color: "#ead7ac"
```

2024-03-18 06:33 UTC, Nixinova commented
```
* linguist.git_submodule.cron.tmbundle
  version: f027bc74d926b[8](https://github.com/github-linguist/linguist/actions/runs/8321971057/job/22769019563?pr=6759#step:6:9)bdc0bfaac22a41[9](https://github.com/github-linguist/linguist/actions/runs/8321971057/job/22769019563?pr=6759#step:6:10)d351bf60edd, filename: /home/runner/work/linguist/linguist/vendor/licenses/git_submodule/cron.tmbundle.dep.yml, license: unknown, allowed: false
    - license needs review: unknown
```
Unsure what to do here. The license of the repo is the following, which is a generic permissive free license:
> Permission to copy, use, modify, sell and distribute this
software is granted. This software is provided "as is" without
express or implied warranty, and with no claim as to its
suitability for any purpose.
What needs to be put as the license for this?

2024-04-09 08:43 UTC, Alhadis commented
> Unsure what to do here. The license of the repo is the following, which is a generic permissive free license

This is the usual license TextMate uses for its grammar repositories; it's a [permissive](https://github.com/github-linguist/linguist/blob/6aed0bd564f55c4f2d987c2e6035eda7aea26375/vendor/licenses/git_submodule/c.tmbundle.dep.yml) license that's been reviewed and whitelisted in other grammars hosted by the @textmate org.

> What needs to be put as the license for this?

<samp>cron.tmbundle.dep.yml</samp> should have the following contents:

```yaml
---
name: cron.tmbundle
version: f027bc74d926b8bdc0bfaac22a419d351bf60edd
type: git_submodule
homepage: https://github.com/textmate/cron.tmbundle
license: permissive
licenses:
- sources: README.mdown
  text: "If not otherwise specified (see below), files in this repository fall under
    the following license:\n\n\tPermission to copy, use, modify, sell and distribute
    this\n\tsoftware is granted. This software is provided "as is" without\n\texpress
    or implied warranty, and with no claim as to its\n\tsuitability for any purpose.\n\nAn
    exception is made for files in readable text which contain their own license information,
    or files where an accompanying file exists (in the same directory) with a “-license”
    suffix added to the base-name name of the original file, and an extension of txt,
    html, or similar. For example “tidy” is accompanied by “tidy-license.txt”."
notices: []
```

🤔 …however, I'm not sure why `bundle exec licensed` isn't picking up the license body automatically when it (ostensibly) had no issues with [<samp>c.tmbundle.dep.yml</samp>](https://github.com/github-linguist/linguist/blob/master/vendor/licenses/git_submodule/c.tmbundle.dep.yml).

<sub>@lildude, hulp.</sub>

2024-04-09 08:44 UTC, Alhadis approved these changes

2024-04-09 09:10 UTC, lildude commented
The cached file has the correct content, we just need to manually set the license as licensed struggles a bit with so cases like this.

2024-04-09 09:11 UTC, lildude commented on vendor/licenses/git_submodule/cron.tmbundle.dep.yml
> +license: unknown
```suggestion
license: permissive
```

2024-06-07 10:33 UTC, merged