Add NMODL Language
github-linguist/linguist pull request #6776
Opened 2024-03-28 10:19 UTC by matz-e

This is the NEURON extension to MODL, a model description language used
within the neuroscientific community.  See also:

https://www.neuron.yale.edu/neuron/static/py_doc/modelspec/programmatic/mechanisms/nmodl2.html

## Description

I am involved in the neuroscientific community around the NEURON simulator.  It has its
own DSL used to describe neuron processes. We have noticed that a lot of the code files
are misclassified as AMPL, and would like to fix that.

The linked search matches 12.7k files, which I think constitutes a strong case to
recognize the language within Github.  I have included two samples from the main NEURON
repository showcasing the syntax.

The extension is shared by kernel modules and AMPL.  I have looked into providing more
samples for the latter, but I am not sure which licenses these examples would be.
Comparing the two languages, they seem very different. Do you have any advise?

I will contact the author(s) of existing syntax highlighting to see if they can provide
their syntax highlighting under a compatible license.

## Checklist:

- [x] **I am adding a new language.**
  - [x] The extension of the new language is used in hundreds of repositories on GitHub.com.
    - Search results for each extension:
      
      -  https://github.com/search?type=code&q=NOT+is%3Afork+path%3A*.mod+NEURON
  - [x] I have included a real-world usage sample for all extensions added in this PR:
    - Sample source(s):
      - https://github.com/neuronsimulator/nrn/blob/master/docs/nmodl/mod/fornetcon.mod
      - https://github.com/neuronsimulator/nrn/blob/master/docs/nmodl/mod/k3st.mod
    - Sample license(s): BSD
  - [ ] I have included a syntax highlighting grammar: [URL to grammar repo]
      
  - [x] I have added a color
    - Hex value: `#00356B`
    - Rationale: Color used by Yale, the primary institution at which NEURON was developed.
  - [ ] I have updated the heuristics to distinguish my language from others using the same extension.

2024-03-28 12:31 UTC, lildude commented
> Comparing the two languages, they seem very different. Do you have any advise?

Yup, add a regex to the list of current heuristics for the `.mod` extension:

https://github.com/github-linguist/linguist/blob/4ac734c15a96f9e16fd12330d0cb8de82274f700/lib/linguist/heuristics.yml#L468-L474

2024-03-30 16:33 UTC, matz-e commented
> > Comparing the two languages, they seem very different. Do you have any advise?
> 
> Yup, add a regex to the list of current heuristics for the `.mod` extension:

Thanks! I added some keywords that would seem fairly safe. Sorry, did not realize it would be relatively simple. Tested the changes on a local repo, too.

2024-03-31 08:10 UTC, lildude requested changes
Can you please update [the test](https://github.com/github-linguist/linguist/blob/4ac734c15a96f9e16fd12330d0cb8de82274f700/test/test_heuristics.rb#L689) for this heuristic too.

2024-04-04 07:53 UTC, matz-e commented
> Can you please update [the test](https://github.com/github-linguist/linguist/blob/4ac734c15a96f9e16fd12330d0cb8de82274f700/test/test_heuristics.rb#L689) for this heuristic too.

OK, added a line there, `bundle exec rake test` and the crosstest seem to come back clean

2024-04-04 11:13 UTC, lildude approved these changes
LGTM. Thanks.

Note: this PR will not be merged until close to when the next release is made. See [here](https://github.com/github/linguist/blob/master/docs/troubleshooting.md#my-linguist-pr-has-been-merged-but-github-doesnt-reflect-my-changes) for more details.

2024-06-07 10:33 UTC, merged