Add KoLmafia ASH with samples and heuristic
github-linguist/linguist pull request #6784
Opened 2024-04-04 10:20 UTC by gausie

## Description
I am currently missing a grammar - the closest thing that exists is here https://raw.githubusercontent.com/danielyxie/vscode-kolmafia-ash/master/syntaxes/ash.yml. How would you recommend I include that?

## Checklist:

- [x] **I am adding a new language.**
  - [x] The extension of the new language is used in hundreds of repositories on GitHub.com.
    - Search results for each extension:
      - https://github.com/search?type=code&q=NOT+is%3Afork+path%3A*.ash+%2F%28%5C%24%5Ba-zA-Z%5D%2B%5C%5B%7Cvisit_url%7Csince+r%5Cd%2B%29%2F
  - [x] I have included a real-world usage sample for all extensions added in this PR:
    - Sample source(s):
      - http://svn.code.sf.net/p/zlib/code/scripts/zlib.ash
      - https://github.com/Veracity0/arrrbor-day/blob/main/scripts/Arrrbor%20Day.ash
    - Sample license(s):
      - None indicated, not typical to do so for this community
  - [x] I have included a syntax highlighting grammar
  - [x] I have added a color
    - Hex value: `#54bd32`
    - Rationale: Green picked from the lime featured in the KoLmafia icon
  - [x] I have updated the heuristics to distinguish my language from others using the same extension.

2024-04-04 11:15 UTC, lildude commented
There's already a PR for this - https://github.com/github-linguist/linguist/pull/5401. Maybe you can contribute to that PR or pull in the changes proposed there, keeping in mind all the comments on that PR.

2024-04-04 11:25 UTC, gausie commented
> There's already a PR for this - #5401. Maybe you can contribute to that PR or pull in the changes proposed there, keeping in mind all the comments on that PR.

Oh wow well done for remembering this. And sorry @midgleyc for missing your work! I think the search I've done, which is just a regex based on the heuristic I wrote, does a better job of reflecting the popularity.

I'll update this PR to use Chris's grammar.

2024-04-04 11:57 UTC, gausie commented
Ok that is done. I note that @midgleyc's PR seems to have run `script/list-grammars` but the guide for adding a new language does not include that as a step - would you like me to do so?

2024-04-04 12:18 UTC, gausie commented
> This is likely to fail the popularity test again -- I think the number of required repos has only increased since my PR several years ago.
> 
> A lot of repositories exist only on Sourceforge, and as GitHub doesn't (seem to?) list repos without recent contributions in the search, finding many of the existing scripts is going to be difficult. Even with them, the language likely isn't popular enough.

The search I have in the description is listing almost 1k files, not sure how to see individual repos but it does seem to be at least a hundred.

It would be really great to differentiate these from AGS Scripts!

2024-04-04 16:31 UTC, lildude requested changes
We can't accept your samples for a few reasons:

1. they're too big; if the diff suppresses them, they're too big for our needs
2. they're not covered by an open source license.

All samples _must_ be covered by an open source license and this must be stated in the template and identifiable at the time in the source repo. We will _not_ accept samples without an indication of their license.

We're also going to need the cached license file. This should have been created when you ran `script/add-grammar` to add the grammar. Please add that file to the PR. If you can't find it, run this command:

https://github.com/github-linguist/linguist/blob/4ac734c15a96f9e16fd12330d0cb8de82274f700/script/add-grammar#L133-L134

As with the other PR, popularity still isn't sufficient for inclusion right now.

2024-04-06 18:43 UTC, Brandylee24 approved these changes

2025-03-12 08:00 UTC, closed without merging