Add common AutoHotkey extensions
github-linguist/linguist pull request #6815
Opened 2024-05-09 03:26 UTC by Banaanae

Adds common AutoHotkey extensions

## Description

Adds the following extensions:
- ah1
- ah2
- ahk1^
- ahk2

^ `ahk1` isn't used in the required amount of repositories, but is the counterpart to `ahk2` which has, if this extension shouldn't be added please let me know.

## Checklist:

- [X] **I am adding a new extension to a language.**
  - [X] The new extension is used in hundreds of repositories on GitHub.com
    - Search results for each extension:
      
      - https://github.com/search?q=NOT+is%3Afork+path%3A*.ahk1+%3A%3D&type=code
      - https://github.com/search?q=NOT+is%3Afork+path%3A*.ahk2+%3A%3D&type=code
      - https://github.com/search?q=NOT+is%3Afork+path%3A*.ah1+%3A%3D&type=code
      - https://github.com/search?q=NOT+is%3Afork+path%3A*.ah2+%3A%3D&type=code
  - [X] I have included a real-world usage sample for all extensions added in this PR:
    - Sample source(s):
      - https://github.com/Gum-Joe/AutoHotkeyScript/blob/master/logitech_g810/premiere/general/old/preset-taran.ahk1
      - https://github.com/cataerogong/keymap/blob/master/exe/keymap.ahk2
      - https://github.com/DonovanZeanah/GlobalCoder/blob/main/GlobalCoder.ah1
      - https://github.com/sxzxs/Real-time-translation-typing/blob/main/thread.ah2
    - Sample license(s):
    - MIT
    - MIT
    - N/A
    - N/A
  - [X] I have included a change to the heuristics to distinguish my language from others using the same extension.

2024-05-09 06:26 UTC, lildude requested changes
A quick look at your search links suggests most of these extensions are nowhere near popular enough for inclusion. Your samples are all exactly what we [explicitly say](https://github.com/github-linguist/linguist/blob/master/CONTRIBUTING.md#adding-an-extension-to-a-language) do not add too.

Please remove all extensions that don't meet our popularity requirements or aren't close. And replace the samples with _real_ samples.

The heuristic is also unnecessary as Linguist won't use it as it doesn't already know about this extension, which means every file on GitHub will that extension will now be associated with this language, which you might want to think twice about.

2024-05-09 21:57 UTC, Banaanae commented
I removed the `ahk1` and `ahk2` extensions
Made the samples better

I'm not too sure what you mean with the heuristics, there are a couple of files like [this](https://github.com/WEC-Sim/WEC-Sim/blob/main/examples/BEMIO/AQWA/RM3/RM3.AH1) which share the same extension, but isn't autohotkey
Overrides sound like a local thing?

2024-05-10 06:08 UTC, lildude commented
> I'm not too sure what you mean with the heuristics, there are a couple of files like [this](https://github.com/WEC-Sim/WEC-Sim/blob/main/examples/BEMIO/AQWA/RM3/RM3.AH1) which share the same extension, but isn't autohotkey

The heuristic is not considered at all when Linguist only knows one language for an extension. In such a case the language Linguist knows is applied to all files with that extension, unless overridden.

In order for the heuristic to be considered, Linguist needs to know of at least two languages using the extension so it can use it to differentiate between the two and make a better identification. So if you want your heuristic to take effect, you will need to identify another  other language, and add it to Linguist as part of this PR, assuming it meets the popularity requirements too.

That file in question will remain unaffected as the repo already has an override.

> Overrides sound like a local thing?

Only local to the repo. The other language file you pointed to only has a language and loose syntax highlighting because the repo owner has told Linguist to consider all files in the repo as matlab with [this line](https://github.com/WEC-Sim/WEC-Sim/blob/453af810b9f1bf5ae3b608b1e84078037dc20919/.gitattributes#L1).

2024-05-10 10:17 UTC, Banaanae commented
All requested changes should be addressed now :)

2026-08-10 11:24 UTC, lildude approved these changes

2026-08-10 11:29 UTC, merged