Add Linguist support for Leo.
github-linguist/linguist pull request #6970
Opened 2024-07-26 21:38 UTC by d0cd

This PR adds Linguist support for the Leo progamming language. Leo is a high-level language that allows developers to use zero-knowledge proofs in their applications while abstracting away the cryptographic complexities. Leo programs are compiled into Aleo instructions, which can be executed on the Aleo blockchain.
 
## References
- [Aleo](https://leo-lang.org/)
- [Developer Documentation](https://docs.leo-lang.org/leo)

## Checklist
- [x]  **I am adding a new language.**
   - [x]  The extension of the new language is used in hundreds of repositories on GitHub.com. https://github.com/search?q=path%3A*main.leo+NOT+owner%3AProvableHQ++NOT+owner%3AAleoNet+NOT+is%3Afork&type=code&p=3. Note that the `main.leo` file is expected to occur once per repository, which meets the requirements outlined [here](https://github.com/github-linguist/linguist/issues/5756).
   - [x]  I have included a real-world usage sample for all extensions added in this PR. They are covered under the license that is tagged at the top of each file.
   - [x] I have included a syntax highlighting grammar: https://github.com/ProvableHQ/leo-linguist/blob/master/syntaxes/Aleo.tmLanguage.json
   - [x]  I have added a color     
       - Hex value: #6814ec
       - Rationale: These are the brand colors.

2024-08-05 17:03 UTC, lildude requested changes
This PR is missing the cached license file generated by this line in the `add-grammar` script:

https://github.com/github-linguist/linguist/blob/39fd5e93de98de3434cb3e857c5b1972c418f8c5/script/add-grammar#L133-L134

Please add it.

2024-08-14 05:05 UTC, lildude commented
> The extension of the new language is used in hundreds of repositories on GitHub.com. https://github.com/search?q=path%3A*main.leo+NOT+owner%3AProvableHQ++NOT+owner%3AAleoNet+NOT+is%3Afork&type=code&p=3. Note that the main.leo file is expected to occur once per repository, which meets the requirements outlined https://github.com/github-linguist/linguist/issues/5756.

This PR is not adding support for a single file, it's adding support for an extension which means the extension criteria applies and as with https://github.com/github-linguist/linguist/pull/6969, it appears quite common for a repo to contain multiple `.leo` files.

It seems quite common for `.leo` files to mention `aleo` so [adding that to filter](https://github.com/search?q=path%3A*.leo+NOT+owner%3AProvableHQ++NOT+owner%3AAleoNet+NOT+is%3Afork+aleo&type=code) out files which clearly aren't Leo (there are a lot of XML files using this extension) indicates things are nearly there.

2024-08-15 15:21 UTC, DecimalTurn commented
Closes #6900

2025-04-22 22:00 UTC, DecimalTurn commented
Might be worth adding a heuristic like `^\s*program\s*[a-zA-Z_0-9\.]*\s*\{` to match the program declaration at the top of `.leo` file. This would give [1.9k files](https://github.com/search?q=NOT+is%3Afork+path%3A*.leo+NOT+owner%3AProvableHQ++NOT+owner%3AAleoNet+%2F%5E%5Cs*program%5Cs*%5Ba-zA-Z_0-9%5C.%5D*%5Cs*%5C%7B%2F&type=code) at the moment which is less than 50% of all `.leo` files.

2025-06-02 08:56 UTC, lildude commented
> Might be worth adding a heuristic like `^\s*program\s*[a-zA-Z_0-9\.]*\s*\{` to match the program declaration at the top of `.leo` files. This would give [1.9k files](https://github.com/search?q=NOT+is%3Afork+path%3A*.leo+NOT+owner%3AProvableHQ++NOT+owner%3AAleoNet+%2F%5E%5Cs*program%5Cs*%5Ba-zA-Z_0-9%5C.%5D*%5Cs*%5C%7B%2F&type=code) at the moment which is less than 50% of all `.leo` files.

The heuristic wouldn't have any effect as this language is the only one with the `.leo` extension. It does however confirm popularity is now good to go.

@d0cd Please merge in master. I can't because your PR has come from an org-owned repo.

2025-06-02 15:04 UTC, d0cd commented
Thanks @lildude! We'll get this updated and merged in by Friday (earlier, if needed).
Are there any deadlines on your end on cutting the next Linguist release?

2025-06-02 15:22 UTC, lildude commented
@d0cd I need to make the release by the end of Thursday, UK time, at the latest.

2025-06-02 16:45 UTC, d0cd commented
Sounds good @lildude, we'll have it in ASAP!
There have been a few updates to the language since making this PR. 
Do you recommend folding those in to this PR or holding off to another one?

2025-06-02 16:48 UTC, lildude commented
> Do you recommend folding those in to this PR or holding off to another one?

It depends. If this is just updating the samples, or grammar (not needed unless it's a completely new repo as we update all grammars with each release) then this PR is fine. If it's modifying the extensions, then any new ones are likely to hold up this PR even longer.

Once this has been merged, users can always use an override for any new extensions.

2025-06-02 17:11 UTC, d0cd commented
Got it, we have some grammar updates but if the release process updates the submodule, then we're good to go!

2025-06-02 19:01 UTC, merged