Add Aiken Language
github-linguist/linguist pull request #6991
Opened 2024-08-12 20:53 UTC by rvcas

- Add [Aiken](https://aiken-lang.org/) programming language to linguist.
- Add [UPLC](https://aiken-lang.org/uplc), Aiken's target language, to linguist.

## Description

## Checklist:

- [ ] **I am adding a new language.**
  - [ ] The extension of the new language is used in hundreds of repositories on GitHub.com.
    - Search results for each extension:
      
      -  https://github.com/search?type=code&q=NOT+is%3Afork+path%3A*.FOOBAR+KEYWORDS
  - [ ] I have included a real-world usage sample for all extensions added in this PR:
    - Sample source(s):
      - [URL to each sample source, if applicable]
    - Sample license(s):
  - [ ] I have included a syntax highlighting grammar: [URL to grammar repo]
      
  - [ ] I have added a color
    - Hex value: `#RRGGBB`
    - Rationale: 
  - [ ] I have updated the heuristics to distinguish my language from others using the same extension.

2024-08-13 07:22 UTC, lildude requested changes
Whoops. Looks like your editor has changed indentation on the languages.yml file making it incredibly hard to review. Please reverse these changes.

Several of your samples are too big too. If the diff suppresses them, they're too big. Please replace these.

2024-08-14 06:18 UTC, lildude submitted a review, later dismissed
Linguist only accepts TextMate compatible grammars. This is mentioned a little further down in the [CONTRIBUTING.md](https://github.com/github-linguist/linguist/blob/master/CONTRIBUTING.md#fixing-syntax-highlighting) file. You should have encountered an error when attempting to add the grammar using the `script/add-grammar` script which should have alerted you to there being problems with the grammar repo.

The lines in `script/list-grammars` are for grammars maintained directly in the highlighting engine completely independently of Linguist. Only GitHub staff know which grammars these are which is why this list exists.

There is currently no way to submit tree-sitter grammars.

Please replace the grammar with a TextMate-compatible grammar.

2024-08-15 10:51 UTC, KtorZ commented
Note: Aiken seems to be a quite popular name in some part of the world, and it's apparently also a file format for writing quizzes (!). For these reasons, I usually prefer [the following query](https://github.com/search?q=path%3A**%2Faiken.toml+NOT+is%3Afork&type=code) which is more strict for filtering out _actual Aiken projects_.

I went ahead and checked results found from Github to ensure we are above the _200_ thresholds mentioned in the CONTRIBUTING.md. I discarded repositories that were empty or had actually no Aiken (`.ak`) files in them, but were only mentioning Aiken. 

<details><summary>See final list</summary>

- https://github.com/0eau/elude
- https://github.com/ADAOcommunity/cardano-vesting-dApp
- https://github.com/Achyut770/AikenSupplyChain
- https://github.com/AdaSouls/Cardano-Soulbound
- https://github.com/AgustinBadi/aiken-merkle-tree
- https://github.com/Ali-Hill/blueprint-experiments
- https://github.com/Anastasia-Labs/aiken-design-patterns
- https://github.com/Anastasia-Labs/aiken-linked-list
- https://github.com/Anastasia-Labs/aiken-merkle-tree
- https://github.com/Anastasia-Labs/aiken-trie
- https://github.com/AngeYobo/htlc-contract-aiken
- https://github.com/Astodialo/unLearn
- https://github.com/Banele78/hello-world-aiken
- https://github.com/Cardano-Fans/acca
- https://github.com/Charli3-Official/oracle-integration-aiken
- https://github.com/Cornucopias/mint-contract
- https://github.com/CryptoSnowPrince/aiken_hello_world
- https://github.com/CryptoSnowPrince/aiken_vesting
- https://github.com/Danogo2023/bond-dex
- https://github.com/Danogo2023/bond-issue
- https://github.com/Danogo2023/daken
- https://github.com/Danysan1/vscode-aiken-sintax-hightlighting
- https://github.com/Deadairx/aiken-hello-world
- https://github.com/Eibbie/hello-world-aiken
- https://github.com/ErickRomeroDev/aiken-example-node
- https://github.com/EzePze/automatic-octo-palm-tree
- https://github.com/FaizanShaikh-3033/Aiken
- https://github.com/Halalend/protocol-analysis
- https://github.com/HeptaSean/aiken-trivial
- https://github.com/Jidooochan/aiken-hello-world
- https://github.com/Jidooochan/aiken-vesting
- https://github.com/KtorZ/aiken-fuzz
- https://github.com/MeshJS/aiken-next-ts-template
- https://github.com/MeshJS/mesh
- https://github.com/MeshJS/mesh-pbl-student-library
- https://github.com/Modulo-P/Cardano-Semaphore
- https://github.com/Modulo-P/ak-128
- https://github.com/Modulo-P/ak-381
- https://github.com/Modulo-P/hydra-node-plutusv3
- https://github.com/Modulo-P/zk-mastermind-aiken
- https://github.com/MynthAI/cnt-burn
- https://github.com/MynthAI/mint-chocolate-chip
- https://github.com/MynthAI/myusd
- https://github.com/NicholasMaselli/SimpleCardanoContract
- https://github.com/NoumenaDigital/carbon-accounting
- https://github.com/OpShin/pyaiken
- https://github.com/OptimFinance/clean-code
- https://github.com/PaimaStudios/paima-engine
- https://github.com/PaimaStudios/projected-nft-whirlpool
- https://github.com/Piefayth/aiken-blog-1-code
- https://github.com/Piefayth/aiken-ide
- https://github.com/Sebpereira33/CoffeeDAO
- https://github.com/SilV-1951742/MP_aiken
- https://github.com/SundaeSwap-finance/aicone
- https://github.com/SundaeSwap-finance/checkpoint-demo
- https://github.com/SundaeSwap-finance/cosponsor
- https://github.com/SundaeSwap-finance/merkle-patricia-forustry
- https://github.com/SundaeSwap-finance/mint-chocolate-chip
- https://github.com/TienTung2501/Aiken-Document
- https://github.com/TienTung2501/Aiken-Learn
- https://github.com/TienTung2501/Aiken-MintNFT
- https://github.com/Vortecsmaster/Aiken_Auction
- https://github.com/Vortecsmaster/EA_AikenExamples
- https://github.com/WinChitiphat/aiken-vesting
- https://github.com/aadafinance/aada_v1_aiken
- https://github.com/actions-marketplace-validations/aiken-lang_setup-aiken
- https://github.com/adacapital/ak-hellow-world
- https://github.com/adalicious/aiken-gift-card
- https://github.com/adrian052/cardano-betting-system
- https://github.com/adrian052/examples-aiken
- https://github.com/aiken-extra/auxlib
- https://github.com/aiken-extra/string_util
- https://github.com/aiken-extra/time_util
- https://github.com/aiken-extra/tx_util
- https://github.com/aiken-lang/aiken
- https://github.com/aiken-lang/aiken-mode
- https://github.com/aiken-lang/aikup
- https://github.com/aiken-lang/auplc
- https://github.com/aiken-lang/awesome-aiken
- https://github.com/aiken-lang/branding
- https://github.com/aiken-lang/editor-integration-nvim
- https://github.com/aiken-lang/fuzz
- https://github.com/aiken-lang/homebrew-tap
- https://github.com/aiken-lang/marlowe
- https://github.com/aiken-lang/merkle-patricia-forestry
- https://github.com/aiken-lang/play
- https://github.com/aiken-lang/prelude
- https://github.com/aiken-lang/setup-aiken
- https://github.com/aiken-lang/site
- https://github.com/aiken-lang/stdlib
- https://github.com/aiken-lang/tree-sitter-aiken
- https://github.com/aiken-lang/trees
- https://github.com/aiken-lang/vscode-aiken
- https://github.com/aiken-lang/zed-aiken
- https://github.com/aleksey-makarov/aiken-auction
- https://github.com/anhoangphuc/aiken_lang-gift_card
- https://github.com/antibody-cardano/singly-satisfiable
- https://github.com/ariady-putra/lock_unlock
- https://github.com/ariady-putra/morbid
- https://github.com/ariady-putra/more_aiken_examples
- https://github.com/ariady-putra/stakable_aiken
- https://github.com/ariady-putra/world
- https://github.com/ava-orange-education/Ultimate-Cardano-Smart-Contracts
- https://github.com/bWorksApp/aiken-hello-world
- https://github.com/bWorksApp/paas-aiken-contracts
- https://github.com/bloxbean/aiken-java-binding
- https://github.com/bloxbean/aiken-jna-wrapper
- https://github.com/bmoore117/aiken-dates
- https://github.com/bsovdat/aiken-smart-contracts
- https://github.com/buixuandinh711/aiken-to-lucid
- https://github.com/buixuandinh711/cardano_counter
- https://github.com/cardano-foundation/aiken-lucid-yaci-dev-kit-starter-kit
- https://github.com/cardano-foundation/cardano-ibc-incubator
- https://github.com/cardano-foundation/cf-cardano-ballot
- https://github.com/cardano-foundation/merkle-tree-java
- https://github.com/cardano-miners/fortuna
- https://github.com/cardano-scaling/aiken-doom
- https://github.com/carlos53093/Aiken_NFT
- https://github.com/cdev-meetup/hello_aiken
- https://github.com/coinecta/staking-contracts
- https://github.com/deltadefi-protocol/hft-aiken-prototype
- https://github.com/encryptedcoins/encoins-core-aiken
- https://github.com/ernest404/hello-world-aiken
- https://github.com/fabianbormann/aiken-payment-splitter
- https://github.com/fallen-icarus/cardano-aftermarket
- https://github.com/fallen-icarus/cardano-loans
- https://github.com/fallen-icarus/cardano-swaps
- https://github.com/free-honey/naumachia
- https://github.com/gclaramunt/AikenExploration
- https://github.com/gimbalabs/ppbl-2024-aiken-examples
- https://github.com/golddydev/aiken-gift-card
- https://github.com/golddydev/aiken-tutorial
- https://github.com/hammadzubair/Auction-dApp
- https://github.com/hammadzubair/Cardano-Aiken
- https://github.com/ilap/bls
- https://github.com/independenceee/aiken-tutorial
- https://github.com/independenceee/cip68
- https://github.com/independenceee/demarket
- https://github.com/iog-edu-argentina-2024/cardano-dev-2024
- https://github.com/jackchuong/test-smart-contract-aiken
- https://github.com/jpg-store/contracts-v3
- https://github.com/kayvank/rust-aiken-flake
- https://github.com/ken-underscore/cardano_loans_aiken
- https://github.com/keyan-m/cardano-recorded-mint
- https://github.com/krszktc/aiken
- https://github.com/lenfiLabs/lenfi-smart-contracts
- https://github.com/levietcuong2602/aiken-tutorials
- https://github.com/linconvidal/vesting_pycardano
- https://github.com/logicalmechanism/aiken-order-book
- https://github.com/logicalmechanism/assist
- https://github.com/logicalmechanism/bundle-sale
- https://github.com/logicalmechanism/distributed_representation
- http [...]

2024-08-15 10:59 UTC, lildude commented
> I went ahead and checked results found from Github to ensure we are above the _200_ threshold mentioned in the CONTRIBUTING.md.

See https://github.com/github-linguist/linguist/issues/5756

> This PR is also adding support for the `.uplc` format which is commonly used around Aiken projects, but far less popular (in the sense that it is rarely committed and pushed on repositories, so likely much below the required threshold for popularity). Shall we split it out of this PR; and come back later once there's a higher need for it?

If this is less likely to reach the usage requirements, then yes, remove it from this PR and add later when it does meet requirements.

2024-08-15 12:43 UTC, KtorZ commented
> @lildude: See https://github.com/github-linguist/linguist/issues/5756

Ho! Didn't see that. So I take it that this is deemed not popular enough due to the lack of _files per extension_. I crunched the number through the GitHub search API, and I arrive at a grand total of _1605_ files which seems indeed insufficient 😞. I suppose we'll have to encourage people to share a bit more of their code in open source. 

<details><summary>See data</summary>

| repository                                                                 | count |
| ---                                                                        | ---   |
| https://github.com/0eau/elude                                              | 5     |
| https://github.com/ADAOcommunity/cardano-vesting-dApp                      | 6     |
| https://github.com/Achyut770/AikenSupplyChain                              | 2     |
| https://github.com/AdaSouls/Cardano-Soulbound                              | 4     |
| https://github.com/AgustinBadi/aiken-merkle-tree                           | 1     |
| https://github.com/Ali-Hill/blueprint-experiments                          | 18    |
| https://github.com/Anastasia-Labs/aiken-design-patterns                    | 17    |
| https://github.com/Anastasia-Labs/aiken-linked-list                        | 6     |
| https://github.com/Anastasia-Labs/aiken-merkle-tree                        | 2     |
| https://github.com/Anastasia-Labs/aiken-trie                               | 5     |
| https://github.com/AngeYobo/htlc-contract-aiken                            | 1     |
| https://github.com/Astodialo/unLearn                                       | 4     |
| https://github.com/Banele78/hello-world-aiken                              | 1     |
| https://github.com/Cardano-Fans/acca                                       | 36    |
| https://github.com/Charli3-Official/oracle-integration-aiken               | 1     |
| https://github.com/Cornucopias/mint-contract                               | 4     |
| https://github.com/CryptoSnowPrince/aiken_hello_world                      | 1     |
| https://github.com/CryptoSnowPrince/aiken_vesting                          | 1     |
| https://github.com/Danogo2023/bond-dex                                     | 19    |
| https://github.com/Danogo2023/bond-issue                                   | 28    |
| https://github.com/Danogo2023/daken                                        | 39    |
| https://github.com/Deadairx/aiken-hello-world                              | 1     |
| https://github.com/Eibbie/hello-world-aiken                                | 1     |
| https://github.com/ErickRomeroDev/aiken-example-node                       | 1     |
| https://github.com/EzePze/automatic-octo-palm-tree                         | 2     |
| https://github.com/FaizanShaikh-3033/Aiken                                 | 4     |
| https://github.com/Halalend/protocol-analysis                              | 5     |
| https://github.com/HeptaSean/aiken-trivial                                 | 1     |
| https://github.com/Jidooochan/aiken-hello-world                            | 1     |
| https://github.com/Jidooochan/aiken-vesting                                | 1     |
| https://github.com/KtorZ/aiken-fuzz                                        | 11    |
| https://github.com/MeshJS/aiken-next-ts-template                           | 1     |
| https://github.com/MeshJS/mesh                                             | 13    |
| https://github.com/MeshJS/mesh-pbl-student-library                         | 1     |
| https://github.com/Modulo-P/Cardano-Semaphore                              | 21    |
| https://github.com/Modulo-P/ak-128                                         | 1     |
| https://github.com/Modulo-P/ak-381                                         | 1     |
| https://github.com/Modulo-P/hydra-node-plutusv3                            | 1     |
| https://github.com/Modulo-P/zk-mastermind-aiken                            | 4     |
| https://github.com/MynthAI/cnt-burn                                        | 12    |
| https://github.com/MynthAI/mint-chocolate-chip                             | 1     |
| https://github.com/MynthAI/myusd                                           | 7     |
| https://github.com/NicholasMaselli/SimpleCardanoContract                   | 5     |
| https://github.com/NoumenaDigital/carbon-accounting                        | 0     |
| https://github.com/OpShin/pyaiken                                          | 0     |
| https://github.com/OptimFinance/clean-code                                 | 16    |
| https://github.com/PaimaStudios/paima-engine                               | 11    |
| https://github.com/PaimaStudios/projected-nft-whirlpool                    | 1     |
| https://github.com/Piefayth/aiken-blog-1-code                              | 4     |
| https://github.com/Piefayth/aiken-ide                                      | 0     |
| https://github.com/Sebpereira33/CoffeeDAO                                  | 1     |
| https://github.com/SilV-1951742/MP_aiken                                   | 2     |
| https://github.com/SundaeSwap-finance/aicone                               | 2     |
| https://github.com/SundaeSwap-finance/checkpoint-demo                      | 1     |
| https://github.com/SundaeSwap-finance/cosponsor                            | 1     |
| https://github.com/SundaeSwap-finance/merkle-patricia-forustry             | 0     |
| https://github.com/SundaeSwap-finance/mint-chocolate-chip                  | 1     |
| https://github.com/TienTung2501/Aiken-Document                             | 0     |
| https://github.com/TienTung2501/Aiken-Learn                                | 4     |
| https://github.com/TienTung2501/Aiken-MintNFT                              | 1     |
| https://github.com/Vortecsmaster/Aiken_Auction                             | 2     |
| https://github.com/Vortecsmaster/EA_AikenExamples                          | 8     |
| https://github.com/WinChitiphat/aiken-vesting                              | 1     |
| https://github.com/aadafinance/aada_v1_aiken                               | 8     |
| https://github.com/actions-marketplace-validations/aiken-lang_setup-aiken  | 0     |
| https://github.com/adacapital/ak-hellow-world                              | 1     |
| https://github.com/adalicious/aiken-gift-card                              | 1     |
| https://github.com/adrian052/cardano-betting-system                        | 4     |
| https://github.com/adrian052/examples-aiken                                | 6     |
| https://github.com/aiken-extra/auxlib                                      | 4     |
| https://github.com/aiken-extra/string_util                                 | 5     |
| https://github.com/aiken-extra/time_util                                   | 11    |
| https://github.com/aiken-extra/tx_util                                     | 1     |
| https://github.com/aiken-lang/aiken                                        | 147   |
| https://github.com/aiken-lang/aiken-mode                                   | 0     |
| https://github.com/aiken-lang/aikup                                        | 0     |
| https://github.com/aiken-lang/auplc                                        | 7     |
| https://github.com/aiken-lang/awesome-aiken                                | 0     |
| https://github.com/aiken-lang/branding                                     | 0     |
| https://github.com/aiken-lang/editor-integration-nvim                      | 0     |
| https://github.com/aiken-lang/fuzz                                         | 2     |
| https://github.com/aiken-lang/homebrew-tap                                 | 0     |
| https://github.com/aiken-lang/marlowe                                      | 2     |
| https://github.com/aiken-lang/merkle-patricia-forestry                     | 6     |
| https://github.com/aiken-lang/play                              [...]

2024-08-15 16:54 UTC, rvcas commented
No problem. Let's wait and see. We're pretty close for both I believe. It'll be time soon. I'll keep this in sync with master in the meantime.

2025-01-07 15:00 UTC, KtorZ commented
Hello @lildude and happy new year! 

I crunched the latest data on this one and ended with **3811** files across **325** projects (from **181** distinct organisations/users), excluding the main compiler's repository which contains various examples and test cases. 

<details><summary>See projects list</summary>

 | repository                                                                                              | count |
 | ---                                                                                                     | ---   |
 | https://github.com/ADAO-Summon/forum-core-aiken                                                         | 13    |
 | https://github.com/ADAO-Summon/v3                                                                       | 2     |
 | https://github.com/ADAOcommunity/AgoraExpansion                                                         | 4     |
 | https://github.com/ADAOcommunity/cardano-vesting-dApp                                                   | 6     |
 | https://github.com/ADAOcommunity/fracada-dapp                                                           | 4     |
 | https://github.com/AdaHold/preview-testnet                                                              | 5     |
 | https://github.com/AdaSouls/Cardano-Soulbound                                                           | 4     |
 | https://github.com/Ali-Hill/blueprint-experiments                                                       | 18    |
 | https://github.com/AnAi1445/Advanced-NFT--Marketplace                                                   | 10    |
 | https://github.com/AnAi1445/Aiken-Lang-Experimental-Smart-Contracts-and-validators                      | 237   |
 | https://github.com/AnAi1445/Aiken-Lang-Experimental-Smart-Contracts-and-validators-with-proof           | 237   |
 | https://github.com/AnAi1445/Aiken-Lang-Experimental-Smart-Contracts-and-validators-with-proof-main-main | 214   |
 | https://github.com/Anastasia-Labs/aiken-design-patterns                                                 | 21    |
 | https://github.com/Anastasia-Labs/aiken-linked-list                                                     | 6     |
 | https://github.com/Anastasia-Labs/aiken-merkle-tree                                                     | 2     |
 | https://github.com/Anastasia-Labs/aiken-upgradable-multisig                                             | 6     |
 | https://github.com/Anastasia-Labs/lucid-evolution                                                       | 6     |
 | https://github.com/Anastasia-Labs/payment-subscription                                                  | 15    |
 | https://github.com/Astodialo/unLearn                                                                    | 4     |
 | https://github.com/Benja272/e2e-dapp                                                                    | 4     |
 | https://github.com/Cardano-Developer-Community-MCU/minihackathon-example-2                              | 1     |
 | https://github.com/Cardano-Fans/acca                                                                    | 36    |
 | https://github.com/CardanoSolutions/zhuli                                                               | 10    |
 | https://github.com/Charli3-Official/oracle-integration-aiken                                            | 1     |
 | https://github.com/ClecknerT/cardano_nft_web_app                                                        | 1     |
 | https://github.com/Cornucopias/mint-contract                                                            | 4     |
 | https://github.com/Cryptonean/Aiken                                                                     | 4     |
 | https://github.com/Cryptonean/Learn_AIken                                                               | 26    |
 | https://github.com/Danogo2023/bond-dex                                                                  | 19    |
 | https://github.com/Danogo2023/bond-issue                                                                | 28    |
 | https://github.com/Danogo2023/daken                                                                     | 24    |
 | https://github.com/DripDropz/perma-lock                                                                 | 2     |
 | https://github.com/EA-Emurgo-Labs/elabs-ccf-loans                                                       | 103   |
 | https://github.com/ErickRomeroDev/aiken-example-node                                                    | 1     |
 | https://github.com/Exkaleburx/kobicoin                                                                  | 22    |
 | https://github.com/FluidTokens/fn-bafin-cardano-sc                                                      | 21    |
 | https://github.com/FluidTokens/ft-cardano-aquarium-sc                                                   | 32    |
 | https://github.com/FluidTokens/ft-cardano-btc-eth-accounts                                              | 4     |
 | https://github.com/Ghost-Capital/lendex-catalyst                                                        | 1     |
 | https://github.com/Halalend/protocol-analysis                                                           | 5     |
 | https://github.com/HelixLabsDev/eigenfi-vault-cardano-v2                                                | 1     |
 | https://github.com/HeptaSean/aiken-trivial                                                              | 1     |
 | https://github.com/JamOnBread/contract                                                                  | 9     |
 | https://github.com/Kammerlo/cardano-typescript-blueprint-generator                                      | 1     |
 | https://github.com/KonmaORG/Karbon-Ledger                                                               | 7     |
 | https://github.com/KubeEcosystem/kubecoinContracts                                                      | 11    |
 | https://github.com/KubeEcosystem/smart-contract-kube                                                    | 11    |
 | https://github.com/LoveLess1212/ChoreoBpmnAiken                                                         | 4     |
 | https://github.com/MAYZGitHub/mayz-otc                                                                  | 5     |
 | https://github.com/MartinSchere/cardano-dapp-template                                                   | 2     |
 | https://github.com/Mavis2103/aiken-stringify                                                            | 3     |
 | https://github.com/MedicRec/MedicRec                                                                    | 40    |
 | https://github.com/MeshJS/aiken-next-ts-template                                                        | 1     |
 | https://github.com/MeshJS/examples                                                                      | 3     |
 | https://github.com/MeshJS/mesh                                                                          | 42    |
 | https://github.com/MeshJS/mesh-aiken-template                                                           | 3     |
 | https://github.com/MeshJS/mesh-pbl-student-library                                                      | 1     |
 | https://github.com/MicroProofs/Bullet                                                                   | 19    |
 | https://github.com/MicroProofs/inverse-whirlpool                                                        | 8     |
 | https://github.com/Modulo-P/Cardano-Semaphore                                                           | 38    |
 | https://github.com/Modulo-P/ak-381                                                                      | 1     |
 | https://github.com/Modulo-P/hydra-node-plutusv3                                                         | 1     |
 | https://github.com/MynthAI/account                                                                      | 11    |
 | https://github.com/MynthAI/cnt-burn                                             [...]

2025-01-07 15:02 UTC, lildude commented
I'll assess popularity again when I start preparing the next release which will be early March.

2025-03-18 17:49 UTC, lildude commented
> I see the March release has been done, and we unfortunately didn't make the cut. So, to track KPIs, I'll keep recording data regularly -- if you don't mind.

I do. Please don't. 

I'd much prefer the search link in the OP to be updated to more accurately reflect what you feel is current usage, but note: it must be for the extensions and/or filenames being added. It can't be for any other file you'd expect to find in the repo as that's not what is being added - we assess usage for each file and extension in isolation as that's how Linguist classifies things.

I don't always have the time to trawl through the entire discussion within PRs to find a better suggested search query, as is the case this time as I had a hard deadline to meet at short notice.

2025-06-02 08:58 UTC, lildude commented
Popularity looks good now. Please merge in `main`. I can't as the PR has been submitted from an org-owned repo.

2025-06-02 16:15 UTC, KtorZ commented
Fantastic news 🥰.

Thanks for bearing with us (me).

2025-06-02 16:24 UTC, rvcas commented
branch updated

2025-06-02 16:55 UTC, merged