Add Flix language
github-linguist/linguist pull request #7010
Opened 2024-08-23 15:27 UTC by sockmaster27

This adds the [Flix](https://flix.dev/) programming language.

Flix is primarily a research project, but has also focused on practical tooling for making the language widely usable, which has helped spark its growing open-source community.

## Checklist:

- [x] **I am adding a new language.**
  - [x] The extension of the new language is used in hundreds of repositories on GitHub.com.
    - Search results for each extension:
      
      -  https://github.com/search?type=code&q=NOT+is%3Afork+path%3A*.flix
  - [x] I have included a real-world usage sample for all extensions added in this PR:
    - Sample sources:
      - https://github.com/mlutze/flixball
      - https://github.com/mlutze/flix-json
    - Sample license:
      - Apache 2.0
  - [x] I have included a syntax highlighting grammar: https://github.com/flix/vscode-flix
      
  - [x] I have added a color
    - Hex value: `#d44a45`
    - Rationale: This is the color used in the language's logo.
  - [ ] I have updated the heuristics to distinguish my language from others using the same extension.

2024-08-30 12:20 UTC, sockmaster27 commented
@lildude 
I can see that you've added the "Pending Popularity" tag even though it looks like the extension has over 2k files.
Would you mind sharing what filters you're using or if you're judging by other criteria? It would be helpful to know :)

2024-08-30 13:58 UTC, sockmaster27 commented
That makes sense, thanks!

2025-02-08 09:44 UTC, magnus-madsen commented
We have had some recent uptake and it looks like we now satisfy the criteria-- although the search is a bit wonky.

2025-07-08 20:33 UTC, saviorand commented
@lildude looking at the search now, I think there are more than 2k files with the filters. Could you please take a look to see if it satisfies the popularity requirement now?

2025-07-08 21:15 UTC, lildude commented
I only re-review language popularity when I make a new release which is approx every 3 months. I'll reassess then.

2025-09-09 13:53 UTC, lildude requested changes
Usage looks good, however you've got merge conflicts. Please resolve the merge conflicts.

2025-09-10 07:48 UTC, sockmaster27 commented
@lildude Should be ready now

2025-09-10 08:23 UTC, lildude requested changes
Please revert the update to the `vendor/grammars/language-xbase` submodule. We only update submodules when we make a release.

2025-09-11 15:35 UTC, saviorand commented
@lildude should be good now?

2025-09-15 15:52 UTC, merged