Carbon language support
github-linguist/linguist pull request #7011
Opened 2024-08-23 22:42 UTC by btdw

Adds support for the Carbon language. Carbon is an experimental language developed by Google.
- [Source code repository (carbon-language/carbon-lang)](https://github.com/carbon-language/carbon-lang)

## Checklist
- [X] **I am adding a new language.**
  - [X] The extension of the new language is used in hundreds of repositories on GitHub.com.
    - Search results for each extension:
      -  https://github.com/search?q=%28path%3A*.carbon+OR+path%3A*.cb%29&type=Code&ref=advsearch&l=&l=
  - [ ] I have included a real-world usage sample for all extensions added in this PR: (Not exactly sure what they mean by this)
    - Sample source(s):
      
    - Sample license(s):
  - [ ] I have included a syntax highlighting grammar
      
  - [X] I have added a color
    - Hex value: `#222222`
    - Rationale: Carbon uses a black circle with a C in it. This is not `#000000`, but they are similar.
  - [X] I have updated the heuristics to distinguish my language from others using the same extension.

2024-08-24 08:56 UTC, lildude requested changes
Please follow the CONTRIBUTING.md instructions. We will also need a search result for each extension.

2024-08-24 17:08 UTC, btdw commented
A basic sample in ``/samples/Carbon``, and .carbon and .cb extensions have been split into seperate search results.

2024-08-25 08:15 UTC, lildude commented
Do you really want to add support without syntax highlighting? Normally the only reason people add support for a language is to get syntax highlighting on GitHub.

2024-08-26 00:42 UTC, btdw commented
> @btdw Usually when we add support for a language that doesn't have a syntax highlighting grammar (or one released under a permissive license), we sometimes use another language's grammar as a fallback that happens to produce "good enough" highlighting. For example, here's one of your Carbon samples highlighted using Rust:

I've experimented with a couple and found the syntax for [V](https://vlang.io) works the best:
```v
package Shapes api;
import Math;

// Circle

class Circle {
    var Radius: f32 = 1;
    const var Diameter: f32 = self.Radius * 2;

    const var Pi: f32 = Math.Pi;

    fn Area() -> self;
    fn Circumference() -> self;
}

fn Circle.Area() -> self {
    return Math.Pi * .Radius ^ 2
}

fn Circle.Circumference() -> self {
    return 2 * Math.Pi * .Radius
}

// Rectangle

class Rectangle {
    var Width: f32 = 3;
    var Height: f32 = 1;

    fn Area() -> self;
}

fn Rectangle.Area() -> self {
    return .Width * .Height;
}

// Square (Note: Provides same functions as "Rectangle" class.)

class Square {
    var Width: f32 = 3;
    var Height: f32 = 1;

    fn Area() -> self;
}

fn Square.Area() -> self {
    return .Width * .Height;
}

// Triangle

class Triangle {
    var Width: f32 = 3;
    var Height: f32 = 3;

    fn Area() -> self;
}

fn Triangle.Area() -> self {
    return (.Width * .Height) / 2;
}

// Hexagon

class Hexagon {
    var Side: f32 = 5;

    fn Area() -> self;
}

fn Hexagon.Area() -> self {
    return ((3 * 1.732) / 2) * .Side ^ 2
}
```

2024-08-26 00:48 UTC, btdw commented
> 
> I've experimented with a couple and found the syntax for [V](https://vlang.io) works the best:
> 

https://github.com/github-linguist/linguist/pull/7011/commits/9bdc91cf76fafacf81c515def9c4aac1214d7321 adds V syntax highlighting to Carbon files

2024-08-26 00:58 UTC, Alhadis requested changes

2024-08-26 00:58 UTC, Alhadis commented on lib/linguist/languages.yml
> +  codemirror_mime_type: text/x-go
Syntax highlighting on GitHub is specified by TextMate scope (<samp>tm_scope</samp>). So you'll need to include the [relevant field](https://github.com/github-linguist/linguist/blob/d190ad88af555bb2ee213aa64205f2b9a97a077d/lib/linguist/languages.yml#L7468):

```suggestion
  ace_mode: golang
  codemirror_mode: go
  codemirror_mime_type: text/x-go
  tm_scope: source.v
```

2024-08-26 01:00 UTC, btdw commented
Thanks for the suggestion, it was committed

2024-08-26 02:00 UTC, Alhadis submitted a review, later dismissed

2024-08-26 02:23 UTC, Alhadis commented
@btdw You'll need to fix the failed test reported [here](https://github.com/github-linguist/linguist/actions/runs/10551669856/job/29230751551?pr=7011#step:5:76). It simply involves updating [`vendor/README.md`](https://github.com/github-linguist/linguist/blob/e24649a2c9a507b29497b88b3b4e9651b9fb07bf/vendor/README.md) to include Carbon in the list. Just add this to the file on line 75:

~~~diff
--- expected
+++ actual
@@ -83,6 +83,7 @@
 - **Cairo:** [xshitaka/atom-language-cairo](https://github.com/xshitaka/atom-language-cairo)
 - **CameLIGO:** [pewulfman/Ligo-grammar](https://github.com/pewulfman/Ligo-grammar)
 - **Cap'n Proto:** [textmate/capnproto.tmbundle](https://github.com/textmate/capnproto.tmbundle)
+- **Carbon:** [0x9ef/vscode-vlang](https://github.com/0x9ef/vscode-vlang)
~~~

2024-08-26 07:25 UTC, lildude approved these changes
LGTM. Thanks.

Note: this PR will not be merged until close to when the next release is made. See [here](https://github.com/github/linguist/blob/master/docs/troubleshooting.md#my-linguist-pr-has-been-merged-but-github-doesnt-reflect-my-changes) for more details.

2024-08-29 14:28 UTC, merged