Add ZenStack language support
github-linguist/linguist pull request #7065
Opened 2024-09-28 03:58 UTC by jiashengguo

## Description
- add grammar for ZenStack language: https://zenstack.dev/
- repo: https://github.com/zenstackhq/zenstack

## Checklist:

- [x] **I am adding a new language.**
  - [x] The extension of the new language is used in hundreds of repositories on GitHub.com.
    - Search results for each extension:
      
      -  https://github.com/search?type=code&q=NOT+is%3Afork+path%3A*.zmodel+model
  - [x] I have included a real-world usage sample for all extensions added in this PR:
    - Sample source(s):
      - https://github.com/jiashengguo/linguist/blob/master/samples/ZenStack/blog.zmodel
      - https://github.com/jiashengguo/linguist/blob/master/samples/ZenStack/saas.zmodel
      - https://github.com/jiashengguo/linguist/blob/master/samples/ZenStack/todo.zmodel
    - Sample license(s):
      - MIT and Apache
  - [x] I have included a syntax highlighting grammar: 
      https://github.com/zenstackhq/zenstack/tree/main/packages/language
      
  - [x] I have added a color
    - Hex value: `#FF7100`
    - Rationale: It's the main color of zenstack website
  - [x] I have updated the heuristics to distinguish my language from others using the same extension.

2024-09-28 05:16 UTC, lildude commented
We don't add frameworks, stacks, libraries or toolkits as their own languages. This project identifies itself as a "Fullstack TypeScript toolkit that enhances Prisma ORM with flexible Authorization layer for RBAC/ABAC/PBAC/ReBAC, offering auto-generated type-safe APIs and frontend hooks." which appears to be entirely Typescript.

2024-09-28 06:57 UTC, jiashengguo commented
@lildude 
Thanks for the explanation. I see the point, but I'd like to make some clarifications. 

1. ZenStack is indeed a TypeScript toolkit, but the language I'd like to add is the ZModel language it uses. ZModel is a domain-specific language (DSL) for defining data models and access policies, which is actually language-agnostic.
[ZModel Language
](https://zenstack.dev/docs/the-complete-guide/part1/zmodel)

2. ZModel is a superset of the Prisma Schema Language (.prisma). Given that Prisma schema is already included in Linguistic, I believe ZModel should also qualify for inclusion. 

3. We once positioned ZenStack to be a "**DSL for defining data and access rules closer to the database**". You can see our Hacker News launch long time ago:
https://news.ycombinator.com/item?id=37750972 
We don’t mind changing our GitHub description to so if it would make some difference. 

4.  To be able to get the syntax highlight is actually repuested by some ZenStack’s users. Below is the issue created by one of them:
[Provide grammar to Linguist project #823](https://github.com/zenstackhq/zenstack/issues/823)  

Since there are already hundreds of users using it, I definitely hope they could get a better DX on GitHub. If you still hold the opinion, may I know what’s the prerequisites it must meet to be qualified for ZModel to get in?

2024-09-28 08:00 UTC, lildude commented
Thanks for the explanation. I’ve reopened it but you need to rename the language to Zmodel as that is what you are adding. Popularity isn’t sufficient for merging now anyway.

2024-09-28 08:02 UTC, lildude requested changes
The language you are adding is zmodel, not Zenstack. Please rename.

2024-09-29 06:38 UTC, jiashengguo commented
> Thanks for the explanation. I’ve reopened it but you need to rename the language to Zmodel as that is what you are adding. Popularity isn’t sufficient for merging now anyway.

Hey @lildude , may I know what the up-to-date polarity assessment criteria is? 
 
According to the assessment mentioned in #5756 

> - At least 2000 files per extension were indexed in the last year (the number you see at the top of the search results) unless the extension is expected to occur only once per repo, then 200 files.
> - with a reasonable distribution across unique :user/:repo combinations assessed by manually and randomly clicking through the results.

For Zmodel,  the extension is expected to occur only once per repo.  Using the search offered in the template, the result is 387 which is more than 200. 
 https://github.com/search?type=code&q=NOT+is%3Afork+path%3A*.zmodel+model 

So, I believe the first rule has been met. Could the issue be with the second rule? If so, is there a specific way I can verify this myself?

2024-09-29 08:10 UTC, lildude commented
> For Zmodel, the extension is expected to occur only once per repo. Using the search offered in the template, the result is 387 which is more than 200.

🤔 that doesn't appear to be the case from a quick look through the search results [like this repo](https://github.com/TunJudge/tun-judge/tree/3ed71a8e1065e9e7a1d33d5257212a43a8d2b4fb/zenstack/entities), or any of the other results where the `.zmodel` file returned is not in the root of the repo. Your own project has more [than one](https://github.com/search?q=repo%3Azenstackhq%2Fzenstack%20path%3A*.zmodel&type=code).

This suggests the files will occur at least once per repo and likely more, hence the first criteria applies.

2024-09-29 08:19 UTC, lildude commented
Of course this all makes sense when you consider Prisma models will be for many DB tables and people prefer to break things up for easier maintenance (and ownership in big monorepos) as is the case I first referenced which is taking full advantage of importing the individual `.vmodel` files in their [`schema.vmodel`](https://github.com/TunJudge/tun-judge/blob/3ed71a8e1065e9e7a1d33d5257212a43a8d2b4fb/zenstack/schema.zmodel).

So I'd say `schema.vmodel` is likely to occur only once per repo, but not the extension by the design of the fact the individual files can be imported as needed.

2024-09-29 09:41 UTC, lildude requested changes
You will also need to rename the directory containing the samples.

2024-09-29 09:41 UTC, lildude commented on lib/linguist/languages.yml
> +ZenStack:
```suggestion
Zmodel:
```

2024-09-29 09:41 UTC, lildude commented on lib/linguist/languages.yml
> +  language_id: 1012829740
This will need to be regenerated after renaming.

2024-09-29 14:38 UTC, jiashengguo commented
@lildude  Thanks for the comments and the detailed explanation.  The comments has been resovled. 

You're right; it is the same case as Prisma, where most users have only one schema file as their database model in the repo. That is the same case for the search result of zmodel. 

The reason we supported multiple schema files because that was a long-requested feature by the user of Prisma when their schema grows to a certain level for better maintenance (Prisma also added preview support recently after we supported it):

[Support for splitting Prisma schema into multiple files #2377](https://github.com/prisma/prisma/issues/2377)

2024-10-17 05:19 UTC, jiashengguo commented
@lildude The changes have been made based on your feedback. Is there anything else I need to do? 

As I mentioned above, since most repos typically have just one schema file unless they break things up for easier maintenance (same for Prisma), I wonder if it might meet the popularity criteria now.  Here is the search for unique repos that use zmodel:

https://github.com/search?type=code&q=NOT+is%3Afork+path%3A*.zmodel+datasource

2024-11-19 03:16 UTC, ymc9 commented
Hello @lildude , any chance we can get this merged soon? Thank you!

2024-11-19 14:28 UTC, lildude commented
I don't review PRs for popularity requirements etc after the initial review until I'm close to making the next release. The next release will be made sometime next week.

2025-03-21 07:47 UTC, israelins85 commented
+1

2025-03-21 07:57 UTC, Lordfirespeed commented
@lildude did this one fall through the cracks?

2025-03-21 08:01 UTC, kikiimdev commented
+1

2025-03-21 08:09 UTC, Azzerty23 commented
When will the request be merged? Looking forward to Zmodel language integration!

2025-03-21 10:36 UTC, andrictham commented
+1! 🙏

2025-03-21 11:53 UTC, lildude commented
NOTE: +1 comments will be flagged. They add no value and don't influence things at all, especially when the PR isn't ready for merging due to failing tests.

> @lildude did this one fall through the cracks?

No. There are failing tests. PRs do not get merged until all tests pass. It is the PR author's responsibility to keep an eye on their PRs and resolve failures and conflicts.

> When will the request be merged? Looking forward to Zmodel language integration!

Once all tests pass. And even then, the changes in this PR will not appear on GitHub until the next release has been made and deployed. See [here](https://github.com/github/linguist/blob/master/docs/troubleshooting.md#my-linguist-pr-has-been-merged-but-github-doesnt-reflect-my-changes) for more details. 

The next release is scheduled for early June 2025.

2025-03-21 19:04 UTC, Lordfirespeed commented
> No. There are failing tests. PRs do not get merged until all tests pass. It is the PR author's responsibility to keep an eye on their PRs and resolve failures and conflicts.
> [...]
> The next release is scheduled for early June 2025.

Thankyou! ♥️

2025-03-21 21:11 UTC, DawidWraga commented
I'd love to see this request be merged soon. I've been using Zenstack for several years now and it's been a delightful DX. It would be really helpful to have syntax highlighting for .zmodel files on Github!

2025-03-22 12:47 UTC, lildude commented
You can save time by running `make test` locally 😉

2025-03-22 15:23 UTC, jiashengguo commented
@lildude Thanks for the reminder, and sorry for the inconvenience! I had some issues with the Ruby environment on my local machine earlier, but I managed to set up a GitHub codespace and successfully passed the test in the end!

Would you please let me know when you plan to review and merge it if possible?  I will keep an eye on it to ensure it doesn’t break again. 😄

2025-06-02 09:24 UTC, merged