Replase bsl grammar source
github-linguist/linguist pull request #7096
Opened 2024-10-17 16:52 UTC by nixel2007

Replace source repo for bsl (1C Enterprise) language

## Description

Since atom was sunset and atom plugin is not maintained anymore, let's get grammar from vscode plugin. 

## Checklist:

- [ ] **I am adding a new extension to a language.**
  - [ ] The new extension is used in hundreds of repositories on GitHub.com
    - Search results for each extension:
      
      - https://github.com/search?type=code&q=NOT+is%3Afork+path%3A*.FOOBAR+KEYWORDS
  - [ ] I have included a real-world usage sample for all extensions added in this PR:
    - Sample source(s):
      - [URL to each sample source, if applicable]
    - Sample license(s):
  - [ ] I have included a change to the heuristics to distinguish my language from others using the same extension.

- [ ] **I am adding a new language.**
  - [ ] The extension of the new language is used in hundreds of repositories on GitHub.com.
    - Search results for each extension:
      
      -  https://github.com/search?type=code&q=NOT+is%3Afork+path%3A*.FOOBAR+KEYWORDS
  - [ ] I have included a real-world usage sample for all extensions added in this PR:
    - Sample source(s):
      - [URL to each sample source, if applicable]
    - Sample license(s):
  - [ ] I have included a syntax highlighting grammar: [URL to grammar repo]
      
  - [ ] I have added a color
    - Hex value: `#RRGGBB`
    - Rationale: 
  - [ ] I have updated the heuristics to distinguish my language from others using the same extension.

- [ ] **I am fixing a misclassified language**
  - [ ] I have included a new sample for the misclassified language:
    - Sample source(s):
      - [URL to each sample source, if applicable]
    - Sample license(s):
  - [ ] I have included a change to the heuristics to distinguish my language from others using the same extension.

- [ ] **I am changing the source of a syntax highlighting grammar**
  - Old: [URL to grammar repo]
  - New: [URL to grammar repo]

- [ ] **I am updating a grammar submodule**
  

- [ ] **I am adding new or changing current functionality**
  
  - [ ] I have added or updated the tests for the new or changed functionality.

- [ ] **I am changing the color associated with a language**
  
  - [ ] I have obtained agreement from the wider language community on this color change.
    - [URL to public discussion]
    - [Optional: URL to official branding guidelines for the language]

2024-10-17 16:57 UTC, lildude requested changes
I'm not sure how you did it, but we only need the cached license from the new grammar. Please remove the others.

2024-10-17 16:58 UTC, nixel2007 commented
@lildude yeah, they came from submodule let me change it.

2024-10-17 17:00 UTC, lildude commented on vendor/licenses/git_submodule/vsc-language-1c-bsl.dep.yml
> +license: other
```suggestion
license: mit
```

2024-10-17 17:02 UTC, nixel2007 commented
@lildude done

2024-10-22 05:59 UTC, nixel2007 commented
Kindly ping @lildude

2024-10-22 06:25 UTC, lildude approved these changes
LGTM. Thanks.

As an aside, there's really no need for the repeated pings. Why? 👇

Note: this PR will not be merged until close to when the next release is made. See [here](https://github.com/github/linguist/blob/master/docs/troubleshooting.md#my-linguist-pr-has-been-merged-but-github-doesnt-reflect-my-changes) for more details.

2024-11-06 08:12 UTC, lildude commented
> How could I test, if new format of grammar works correctly? Thanks in advance.

Replace the grammar with itself like you did when replacing the old grammar with the new.

2024-11-25 14:57 UTC, lildude approved these changes

2024-11-25 15:59 UTC, merged