Make .bzlmod handled by Starlark
github-linguist/linguist pull request #7121
Opened 2024-11-03 11:24 UTC by petemounce

Bazel's bzlmod dependency manager involves Starlark files with `.bzlmod` file extensions.

https://bazel.build/external/migration#workspace.bzlmod

## Description

## Checklist:

- [x] **I am adding a new extension to a language.**
  - [x] The new extension is used in hundreds of repositories on GitHub.com
    - Search results for each extension:

      Please note: bazel-y people tend toward monorepos, so high contributor count vs smaller repo count

      - 8k repos: https://github.com/search?type=code&q=NOT+is%3Afork+path%3A*.bzlmod+bazel
      - 108 repos: https://github.com/search?type=code&q=NOT+is%3Afork+path%3A*.bzlmod+bzlmod
  - [x] I have included a real-world usage sample for all extensions added in this PR:
    - Sample source(s):
      - https://github.com/bazel-contrib/rules_dotnet/pull/460 -> https://github.com/bazel-contrib/rules_dotnet/blob/master/examples/WORKSPACE.bzlmod
    - Sample license(s):
  - > [ ] I have included a change to the heuristics to distinguish my language from others using the same extension.
  
      Sorry, I don't follow what this one is asking?

2024-11-03 14:11 UTC, lildude requested changes
The sample needs to be added to this PR.

The docs you referenced also only mentions `WORKSPACE.bzlmod` and excluding this file from search returns only 7 files, six of which are owned by the same repo so I think it's probably better to add this as a new named file for now and not as a new extension.

2024-11-03 20:38 UTC, petemounce commented
@lildude many thanks for the fast turnaround.

I haven't understood what to do about the sample license(s) part; how to proceed there?

I've adjusted to only aim for `WORKSPACE.bzlmod`.

2024-11-25 14:53 UTC, lildude commented
> I've adjusted to only aim for `WORKSPACE.bzlmod`.

Thanks. We still need a sample.

2024-11-25 20:59 UTC, petemounce commented
@lildude is something like ln 9650c7c what you have in mind?

2024-11-26 16:57 UTC, merged