Update the grammar used for Dune
github-linguist/linguist pull request #7126
Opened 2024-11-12 12:43 UTC by huwaireb

## Description
Migrates to the official OCaml vscode extension's TextMate grammar for Dune. And adds `dune` and `dune-workspace` to the files to be recognized.

## Checklist:

- [ ] **I am adding a new extension to a language.**
  - [ ] The new extension is used in hundreds of repositories on GitHub.com
    - Search results for each extension:
      
      - https://github.com/search?type=code&q=NOT+is%3Afork+path%3A*.FOOBAR+KEYWORDS
  - [ ] I have included a real-world usage sample for all extensions added in this PR:
    - Sample source(s):
      - [URL to each sample source, if applicable]
    - Sample license(s):
  - [ ] I have included a change to the heuristics to distinguish my language from others using the same extension.

- [ ] **I am adding a new language.**
  - [ ] The extension of the new language is used in hundreds of repositories on GitHub.com.
    - Search results for each extension:
      
      -  https://github.com/search?type=code&q=NOT+is%3Afork+path%3A*.FOOBAR+KEYWORDS
  - [ ] I have included a real-world usage sample for all extensions added in this PR:
    - Sample source(s):
      - [URL to each sample source, if applicable]
    - Sample license(s):
  - [ ] I have included a syntax highlighting grammar: [URL to grammar repo]
      
  - [ ] I have added a color
    - Hex value: `#RRGGBB`
    - Rationale: 
  - [ ] I have updated the heuristics to distinguish my language from others using the same extension.

- [ ] **I am fixing a misclassified language**
  - [ ] I have included a new sample for the misclassified language:
    - Sample source(s):
      - [URL to each sample source, if applicable]
    - Sample license(s):
  - [ ] I have included a change to the heuristics to distinguish my language from others using the same extension.

- [x] **I am changing the source of a syntax highlighting grammar**
  - Old: https://github.com/maelvls/vscode-dune
  - New: https://github.com/ocamllabs/vscode-ocaml-platform

- [ ] **I am updating a grammar submodule**
  

- [ ] **I am adding new or changing current functionality**
  
  - [ ] I have added or updated the tests for the new or changed functionality.

- [ ] **I am changing the color associated with a language**
  
  - [ ] I have obtained agreement from the wider language community on this color change.
    - [URL to public discussion]
    - [Optional: URL to official branding guidelines for the language]

2024-11-12 12:48 UTC, huwaireb commented
There's one non-blocking issue with this update, 

vscode-ocaml-platform has three textmate grammars for dune: 
- `source.dune`
- `source.dune-project`
- `source.dune-workspace`

`dune-project` and `dune-workspace` essentially include `dune`, but extend it with their own "stanzas" or rules per say. And don't include the stanzas supported in `dune` files.  Simply what's common.

However, since linguist offers no way to use multiple grammars per language, the only way is to merge these there into a single tmLanguage.json grammar.

cc @smorimoto

2024-11-12 13:37 UTC, lildude requested changes
Please update the template to fill in the appropriate section for adding the other filenames, You need to fill out _all_ that apply and this is not a simple grammar switch with these additions.

Please note, if any of these new files do not meet our usage requirements, this PR will be blocked until they do meet our requirements or they are removed from this PR. Accordingly, you might want to consider splitting this PR into two.

2024-11-12 13:39 UTC, lildude commented
> * source.dune

This will be the only grammar used and it will be applied to _all_ files identified as Dune as per the `tm_scope: source.dune` in the `language.yml`. Multiple grammars can no apply to the same language. The same grammar can however apply to multiple languages.

2024-11-12 13:44 UTC, huwaireb commented
> Please update the template to fill in the appropriate section for adding the other filenames, You need to fill out _all_ that apply and this is not a simple grammar switch with these additions.

I've updated the PR to reflect.

> Please note, if any of these new files do not meet our usage requirements, this PR will be blocked until they do meet our requirements or they are removed from this PR. Accordingly, you might want to consider splitting this PR into two.

They meet the requirements.

2024-11-25 14:51 UTC, lildude commented
> They meet the requirements, except for `dune-workspace.dev` which only has 75 results. I can remove that, but most use of `dune-workspace` will revolve around it being scoped like that.

You'll need to remove this filename if you want this PR merged.

2024-11-25 16:51 UTC, huwaireb commented
> Looks like you might not have used the `script/add-grammar` command to replace the grammar.

Mm, i'm pretty sure i had, but it was weird. It didn't generate some files, i had to replace them manually.

2024-11-25 17:07 UTC, huwaireb commented
Should be okay now? Just missed deleting the actual submodule.

2024-11-25 17:11 UTC, lildude commented
Please use the script. It correctly orders things in various files that are automatically maintained by it. It also validates the grammar files.

This should do the trick:

```console
script/add-grammar --replace vendor/grammars/vscode-ocaml-platform https://github.com/ocamllabs/vscode-ocaml-platform.git
```

2024-11-25 17:23 UTC, huwaireb commented
> Please use the script. It correctly orders things in various files that are automatically maintained by it. It also validates the grammar files.
> 
> This should do the trick:
> 
> ```
> script/add-grammar --replace vendor/grammars/vscode-ocaml-platform https://github.com/ocamllabs/vscode-ocaml-platform.git
> ```

<img width="1514" alt="Screenshot 2024-11-25 at 21 22 40" src="https://github.com/user-attachments/assets/7057bc35-4a21-45e4-852b-8c3540827b41">

That did not do the trick

2024-11-25 17:25 UTC, huwaireb commented
<img width="1514" alt="Screenshot 2024-11-25 at 21 25 14" src="https://github.com/user-attachments/assets/559c8c6e-0ca0-4ecf-9420-987cf1de05ac">

2024-11-25 18:40 UTC, huwaireb commented
@lildude, quick question relating to the previous non-blocking issue I mentioned.

If I have a new tmLanguage.json syntax file that includes other patterns as follows
```json
{ 
"name": "dune-all",
"scopeName": "source.dune-all",
"fileTypes": ["dune", "dune-project", "dune-workspace"],
"patterns": [{ "include": "source.dune#general" }, { "include": "source.dune#stanzas" }, { "include": "source.dune-project#stanzas" }, { "include": "source.dune-workspace#stanzas" }],
}
```

would that work? These "sources" come from the same submodule.

2024-11-28 06:41 UTC, Alhadis commented
> would that work with linguist? These "sources" come from the same submodule.

@huwaireb Yes. In fact, the largest grammar repository I maintain, [`language-etc`](https://github.com/Alhadis/language-etc), makes extensive use of [`include: "etc#…"`](https://github.com/Alhadis/language-etc/blob/master/grammars/etc.cson) directives to drastically cut down on repeated/mostly-identical pattern rules. Which is particularly pertinent for a repository that mostly contains grammars to highlight assorted config files and data formats. 😉

2025-04-11 12:39 UTC, closed without merging