feat: add c3 support
github-linguist/linguist pull request #7148
Opened 2024-12-04 21:54 UTC by vkuprin

## Description
Adding support for the C3 programming language - a modern systems programming language building on C's foundation. C3 enhances C with features like modules, better error handling, generics, and contracts while maintaining C's performance characteristics.

## Checklist:
- [x] **I am adding a new language.**
  - [x] The extension of the new language is used in hundreds of repositories on GitHub.com.
    - Search results for each extension:
      - https://github.com/search?type=code&q=NOT+is%3Afork+path%3A*.c3+module
      - https://github.com/search?type=code&q=NOT+is%3Afork+path%3A*.c3i+module
      - https://github.com/search?type=code&q=NOT+is%3Afork+path%3A*.c3l+module
      - https://github.com/search?type=code&q=NOT+is%3Afork+path%3A*.c3d+module
  - [x] I have included a real-world usage sample for all extensions added in this PR:
    - Sample source(s):
      - Official C3 language examples from https://c3-lang.org/
    - Sample license(s):
      - MIT License (from C3 language examples)
  - [x] I have included a syntax highlighting grammar: https://github.com/c3lang/c3grammar
  - [x] I have added a color
    - Hex value: `#555555`
    - Rationale: The color represents C3's nature as a systems language while differentiating it from C's traditional blue colors
  - [x] I have updated the heuristics to distinguish my language from others using the same extension.

The C3 language (https://c3-lang.org/) is a modern systems programming language designed to be a better C. This PR adds support for recognizing and highlighting C3 source files on GitHub.

Features demonstrated in the sample:
- Module system
- Enums and structs
- Error handling with faults
- Function contracts
- Defer statements
- Modern control structures

2024-12-05 07:17 UTC, lildude requested changes
You have not followed the instructions for adding a language as detailed in the CONTRIBUTING.md file. Please do so.

2024-12-11 17:10 UTC, oculidev commented
> If anyone has suggestions or tools that could assist with this process, I’d greatly appreciate the input

Chances are you could steal C's textmate grammar, or just fork the c.tmbundle repository and adapt it a little to C3's syntax. https://github.com/textmate/c.tmbundle

2025-02-11 22:33 UTC, xxami commented
@vkuprin Do you still have any interest in pursuing this? I noticed some other PRs are using VSCode configurations (ie. [this vlang one](https://github.com/vlang/vscode-vlang/tree/0d7778ffc6d524f867cdd72027d99ceb5687fe0f)) which is textmate compatible I think? there is a C3 one [here](https://github.com/c3lang/vscode-c3/tree/main/syntaxes) here.

Happy to help trying to hack this in if needed. lmk!

2025-02-11 22:41 UTC, vkuprin commented
> @vkuprin Do you still have any interest in pursuing this? I noticed some other PRs are using VSCode configurations (ie. [this vlang one](https://github.com/vlang/vscode-vlang/tree/0d7778ffc6d524f867cdd72027d99ceb5687fe0f)) which is textmate compatible I think? there is a C3 one [here](https://github.com/c3lang/vscode-c3/tree/main/syntaxes) here.
> 
> Happy to help trying to hack this in if needed. lmk!

Still very interested in the C3 support and the project overall, but I’m currently strapped for time. Please feel free to move forward

2025-05-31 11:58 UTC, closed without merging